const theme=new URLSearchParams(location.search).get('theme');
if(theme==='blue'||theme==='green'){document.body.classList.add('theme-blue');if(theme==='green')document.body.classList.add('theme-green')}
document.querySelectorAll('[data-theme-link]').forEach(link=>{if(theme)link.href=`${link.getAttribute('href').split('?')[0]}?theme=${encodeURIComponent(theme)}`});
const customers=[
 {name:'Mathilda Bell',phone:'0803 474 3348',email:'mathilda@apexretail.ng',company:'Apex Retail',created:'16 Mar 2026'},
 {name:'Ryan Stevens',phone:'0814 362 8940',email:'ryan@northstar.ng',company:'Northstar Foods',created:'25 Mar 2026'},
 {name:'Loretta Myers',phone:'0705 711 3369',email:'loretta@cobalt.ng',company:'Cobalt Studio',created:'18 Apr 2026'},
 {name:'Carrie Aguilar',phone:'0906 616 5266',email:'carrie@apexretail.ng',company:'Apex Retail',created:'12 May 2026'},
 {name:'Marion Rose',phone:'0810 928 5407',email:'marion@smiledigital.ng',company:'Smile Digital',created:'29 May 2026'},
 {name:'Duane Harrison',phone:'0704 447 9642',email:'duane@oseram.ng',company:'Oseram',created:'18 Jun 2026'},
 {name:'William Curtis',phone:'0802 733 9486',email:'william@oseram.ng',company:'Oseram',created:'12 Jul 2026'},
 {name:'Edwin Hampton',phone:'0912 352 9481',email:'edwin@motherearth.ng',company:'Mother Earth',created:'23 Jul 2026'},
 {name:'Adaeze Okafor',phone:'0809 114 6205',email:'adaeze@verveworks.ng',company:'Verve Works',created:'02 Aug 2026'},
 {name:'Tunde Adebayo',phone:'0703 588 4102',email:'tunde@northstar.ng',company:'Northstar Foods',created:'08 Aug 2026'},
 {name:'Ifeoma Eze',phone:'0816 227 9014',email:'ifeoma@cobalt.ng',company:'Cobalt Studio',created:'14 Aug 2026'},
 {name:'Chidi Nwosu',phone:'0902 631 7820',email:'chidi@apexretail.ng',company:'Apex Retail',created:'19 Aug 2026'},
 {name:'Amina Bello',phone:'0805 994 1736',email:'amina@smiledigital.ng',company:'Smile Digital',created:'25 Aug 2026'},
 {name:'Seyi Ogunleye',phone:'0706 348 5521',email:'seyi@motherearth.ng',company:'Mother Earth',created:'01 Sep 2026'},
 {name:'Nneka Obi',phone:'0813 710 4668',email:'nneka@verveworks.ng',company:'Verve Works',created:'06 Sep 2026'},
 {name:'Femi Balogun',phone:'0908 245 1397',email:'femi@oseram.ng',company:'Oseram',created:'11 Sep 2026'},
 {name:'Zainab Musa',phone:'0807 602 8841',email:'zainab@northstar.ng',company:'Northstar Foods',created:'14 Sep 2026'},
 {name:'Kunle Peters',phone:'0701 883 4206',email:'kunle@apexretail.ng',company:'Apex Retail',created:'16 Sep 2026'}
];
const rows=document.querySelector('#customerRows'),empty=document.querySelector('#emptyCustomers'),search=document.querySelector('#customerSearch'),companyFilter=document.querySelector('#companyFilter');
const initials=name=>name.split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase();
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const pageSize=6;let currentPage=1;
function render(){const query=search.value.trim().toLowerCase(),company=companyFilter.value,filtered=customers.filter(customer=>(!company||customer.company===company)&&Object.values(customer).some(value=>value.toLowerCase().includes(query))),pageCount=Math.max(1,Math.ceil(filtered.length/pageSize));currentPage=Math.min(currentPage,pageCount);const first=(currentPage-1)*pageSize,pageRows=filtered.slice(first,first+pageSize);rows.innerHTML=pageRows.map(customer=>`<tr><td><span class="customer-name"><span class="customer-avatar">${initials(customer.name)}</span>${escapeHtml(customer.name)}</span></td><td>${escapeHtml(customer.phone)}</td><td title="${escapeHtml(customer.email)}">${escapeHtml(customer.email)}</td><td>${escapeHtml(customer.company)}</td><td>${escapeHtml(customer.created)}</td><td><button class="customer-menu" type="button" data-index="${customers.indexOf(customer)}" aria-label="Actions for ${escapeHtml(customer.name)}">•••</button></td></tr>`).join('');empty.hidden=filtered.length>0;document.querySelector('#customerCount').textContent=filtered.length;document.querySelector('#paginationSummary').textContent=filtered.length?`Showing ${first+1}–${Math.min(first+pageSize,filtered.length)} of ${filtered.length} customers`:'Showing 0 customers';document.querySelector('#paginationPages').innerHTML=Array.from({length:pageCount},(_,index)=>`<button type="button" class="page-number ${index+1===currentPage?'active':''}" data-page="${index+1}" aria-label="Page ${index+1}" ${index+1===currentPage?'aria-current="page"':''}>${index+1}</button>`).join('');document.querySelector('#previousPage').disabled=currentPage===1;document.querySelector('#nextPage').disabled=currentPage===pageCount}
[...new Set(customers.map(customer=>customer.company))].sort().forEach(company=>companyFilter.add(new Option(company,company)));
search.addEventListener('input',()=>{currentPage=1;render()});companyFilter.addEventListener('change',()=>{currentPage=1;render();closeFilter()});
const filterPanel=document.querySelector('#filterPanel'),filterButton=document.querySelector('#filterButton');function closeFilter(){filterPanel.hidden=true;filterButton.setAttribute('aria-expanded','false')}filterButton.addEventListener('click',()=>{const opening=filterPanel.hidden;if(!opening)return closeFilter();const rect=filterButton.getBoundingClientRect();filterPanel.hidden=false;filterPanel.style.left=Math.max(14,Math.min(innerWidth-324,rect.right-310))+'px';filterPanel.style.top=rect.bottom+7+'px';filterButton.setAttribute('aria-expanded','true')});document.querySelector('#clearFilter').addEventListener('click',()=>{companyFilter.value='';currentPage=1;render();closeFilter()});document.addEventListener('click',event=>{if(!filterPanel.hidden&&!filterPanel.contains(event.target)&&!filterButton.contains(event.target))closeFilter()});
document.querySelector('#paginationPages').addEventListener('click',event=>{const page=event.target.dataset.page;if(page){currentPage=Number(page);render()}});document.querySelector('#previousPage').addEventListener('click',()=>{if(currentPage>1){currentPage--;render()}});document.querySelector('#nextPage').addEventListener('click',()=>{currentPage++;render()});
const dialog=document.querySelector('#customerDialog'),form=document.querySelector('#customerForm'),dialogTitle=document.querySelector('#customerDialogTitle'),dialogIntro=document.querySelector('#customerDialogIntro'),saveCustomer=document.querySelector('#saveCustomer');let editingIndex=null;
function openCustomer(mode='add',index=null){editingIndex=mode==='edit'?index:null;const customer=index===null?null:customers[index];form.reset();form.querySelectorAll('input').forEach(input=>{input.disabled=mode==='view';if(customer)input.value=customer[input.name]});dialogTitle.textContent=mode==='add'?'Add customer':mode==='edit'?'Edit customer':'Customer details';dialogIntro.textContent=mode==='add'?'Create a new customer record.':mode==='edit'?'Update this customer record.':'Review the customer’s contact information.';saveCustomer.hidden=mode==='view';saveCustomer.textContent=mode==='edit'?'Save changes':'Add customer';document.querySelector('#cancelCustomer').textContent=mode==='view'?'Close':'Cancel';dialog.showModal()}
document.querySelector('#addCustomer').addEventListener('click',()=>openCustomer());document.querySelector('#closeCustomerDialog').addEventListener('click',()=>dialog.close());document.querySelector('#cancelCustomer').addEventListener('click',()=>dialog.close());form.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));if(editingIndex===null){customers.unshift({...values,created:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date())});showToast('Customer added')}else{customers[editingIndex]={...customers[editingIndex],...values};showToast('Customer updated')}form.reset();dialog.close();render()});
const toast=document.querySelector('#customerToast');let toastTimer;function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
const rowActions=document.querySelector('#rowActions');let actionIndex=null;rows.addEventListener('click',event=>{const button=event.target.closest('.customer-menu');if(!button)return;actionIndex=Number(button.dataset.index);const rect=button.getBoundingClientRect();rowActions.style.left=Math.max(8,rect.right-150)+'px';rowActions.style.top=Math.min(innerHeight-120,rect.bottom+5)+'px';rowActions.hidden=false});rowActions.addEventListener('click',event=>{const action=event.target.dataset.action;if(!action)return;rowActions.hidden=true;if(action==='view')openCustomer('view',actionIndex);if(action==='edit')openCustomer('edit',actionIndex);if(action==='delete'){const name=customers[actionIndex].name;customers.splice(actionIndex,1);render();showToast(`${name} deleted`)}});document.addEventListener('click',event=>{if(!rowActions.contains(event.target)&&!event.target.closest('.customer-menu'))rowActions.hidden=true});
const sidebar=document.querySelector('#sidebar'),toggle=document.querySelector('.sidebar-toggle'),mobileMenu=document.querySelector('.customers-mobile-menu'),backdrop=document.querySelector('.drawer-backdrop'),mobile=matchMedia('(max-width:760px)');let collapsed=false;
function sync(){const expanded=mobile.matches?sidebar.classList.contains('open'):!collapsed;toggle.setAttribute('aria-expanded',String(expanded));document.querySelector('.customers-app').classList.toggle('sidebar-collapsed',!mobile.matches&&collapsed)}
toggle.addEventListener('click',()=>{if(mobile.matches){sidebar.classList.toggle('open');backdrop.hidden=!sidebar.classList.contains('open')}else collapsed=!collapsed;sync()});mobileMenu.addEventListener('click',()=>{sidebar.classList.add('open');backdrop.hidden=false;sync()});backdrop.addEventListener('click',()=>{sidebar.classList.remove('open');backdrop.hidden=true;sync()});mobile.addEventListener('change',()=>{sidebar.classList.remove('open');backdrop.hidden=true;sync()});sync();render();
