const theme=new URLSearchParams(location.search).get('theme');
if(theme==='blue'||theme==='green'){document.body.classList.add('theme-blue');if(theme==='green')document.body.classList.add('theme-green')}
document.querySelectorAll('[data-theme-link]').forEach(link=>{if(theme)link.href=`${link.getAttribute('href').split('?')[0]}?theme=${encodeURIComponent(theme)}`});
const products=[
 {icon:'⌚',name:'Silver Watch',supplier:'Vinta Supplier',type:'Watch',brand:'Vinta',stock:12,variants:2,status:'Active'},
 {icon:'👕',name:'Cotton T-shirt',supplier:'Vinta Supplier',type:'Shirt',brand:'Vinta',stock:67,variants:4,status:'Active'},
 {icon:'💍',name:'Diamond Ring',supplier:'Apex Supplier',type:'Ring',brand:'Aurelia',stock:23,variants:1,status:'Active'},
 {icon:'🧥',name:'Sweatshirt Hoodie',supplier:'Northstar Supply',type:'Outerwear',brand:'Northstar',stock:67,variants:1,status:'Active'},
 {icon:'👗',name:'Cocktail Dress',supplier:'Northstar Supply',type:'Dress',brand:'Aurelia',stock:120,variants:2,status:'Active'},
 {icon:'👟',name:'Oldskool Vans',supplier:'Vinta Supplier',type:'Footwear',brand:'Vans',stock:67,variants:2,status:'Active'},
 {icon:'📷',name:'Mirrorless Camera',supplier:'Cobalt Trade',type:'Camera',brand:'Canon',stock:12,variants:1,status:'Active'},
 {icon:'👠',name:'ES High Heel',supplier:'Apex Supplier',type:'Footwear',brand:'Aurelia',stock:23,variants:4,status:'Active'},
 {icon:'🥿',name:'Leather Flats',supplier:'Apex Supplier',type:'Footwear',brand:'Aurelia',stock:34,variants:1,status:'Draft'},
 {icon:'🎒',name:'Travel Backpack',supplier:'Vinta Supplier',type:'Backpack',brand:'Vinta',stock:67,variants:2,status:'Active'},
 {icon:'🎧',name:'Studio Headphones',supplier:'Cobalt Trade',type:'Audio',brand:'Sonora',stock:18,variants:3,status:'Archived'}
];
const rows=document.querySelector('#productRows'),empty=document.querySelector('#emptyProducts'),search=document.querySelector('#productSearch'),selectAll=document.querySelector('#selectAllProducts');
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const selected=new Set();let currentView='active',currentPage=1;const pageSize=7;
function filteredProducts(){const query=search.value.trim().toLowerCase();return products.filter(product=>(currentView==='all'||product.status==='Active')&&Object.values(product).some(value=>String(value).toLowerCase().includes(query)))}
function render(){const filtered=filteredProducts(),pageCount=Math.max(1,Math.ceil(filtered.length/pageSize));currentPage=Math.min(currentPage,pageCount);const first=(currentPage-1)*pageSize,pageRows=filtered.slice(first,first+pageSize);rows.innerHTML=pageRows.map(product=>{const index=products.indexOf(product),statusClass=product.status.toLowerCase();return `<tr><td><input type="checkbox" data-select-index="${index}" aria-label="Select ${escapeHtml(product.name)}" ${selected.has(index)?'checked':''}></td><td><span class="product-name"><span class="product-thumb" aria-hidden="true">${product.icon}</span>${escapeHtml(product.name)}</span></td><td>${escapeHtml(product.supplier)}</td><td>${escapeHtml(product.type)}</td><td>${escapeHtml(product.brand)}</td><td><span class="stock-value">${product.stock}</span> in ${product.variants} ${product.variants===1?'variant':'variants'}</td><td><span class="product-status ${statusClass}">${escapeHtml(product.status)}</span></td><td><button class="customer-menu" type="button" data-index="${index}" aria-label="Actions for ${escapeHtml(product.name)}">•••</button></td></tr>`}).join('');empty.hidden=filtered.length>0;document.querySelector('#productCount').textContent=filtered.length;document.querySelector('#activeCount').textContent=products.filter(product=>product.status==='Active').length;document.querySelector('#allCount').textContent=products.length;document.querySelector('#paginationSummary').textContent=filtered.length?`Showing ${first+1}–${Math.min(first+pageSize,filtered.length)} of ${filtered.length} products`:'Showing 0 products';document.querySelector('#paginationPages').innerHTML=Array.from({length:pageCount},(_,index)=>`<button type="button" class="page-number ${index+1===currentPage?'active':''}" data-page="${index+1}" ${index+1===currentPage?'aria-current="page"':''}>${index+1}</button>`).join('');document.querySelector('#previousPage').disabled=currentPage===1;document.querySelector('#nextPage').disabled=currentPage===pageCount;selectAll.checked=pageRows.length>0&&pageRows.every(product=>selected.has(products.indexOf(product)));selectAll.indeterminate=!selectAll.checked&&pageRows.some(product=>selected.has(products.indexOf(product)))}
search.addEventListener('input',()=>{currentPage=1;render()});
document.querySelector('.inventory-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(!button)return;currentView=button.dataset.view;currentPage=1;document.querySelectorAll('[data-view]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});render()});
rows.addEventListener('change',event=>{const checkbox=event.target.closest('[data-select-index]');if(!checkbox)return;const index=Number(checkbox.dataset.selectIndex);checkbox.checked?selected.add(index):selected.delete(index);render()});
selectAll.addEventListener('change',()=>{filteredProducts().slice((currentPage-1)*pageSize,currentPage*pageSize).forEach(product=>{const index=products.indexOf(product);selectAll.checked?selected.add(index):selected.delete(index)});render()});
document.querySelector('#paginationPages').addEventListener('click',event=>{if(event.target.dataset.page){currentPage=Number(event.target.dataset.page);render()}});document.querySelector('#previousPage').addEventListener('click',()=>{if(currentPage>1){currentPage--;render()}});document.querySelector('#nextPage').addEventListener('click',()=>{currentPage++;render()});
const dialog=document.querySelector('#productDialog'),form=document.querySelector('#productForm'),dialogTitle=document.querySelector('#productDialogTitle'),dialogIntro=document.querySelector('#productDialogIntro'),save=document.querySelector('#saveProduct');let editingIndex=null;
function openProduct(mode='add',index=null){editingIndex=mode==='edit'?index:null;const product=index===null?null:products[index];form.reset();form.querySelectorAll('input,select').forEach(field=>{field.disabled=mode==='view';if(product&&field.name)field.value=product[field.name]});dialogTitle.textContent=mode==='add'?'Add product':mode==='edit'?'Edit product':'Product details';dialogIntro.textContent=mode==='add'?'Create a new inventory record.':mode==='edit'?'Update this inventory record.':`${product.stock} units across ${product.variants} ${product.variants===1?'variant':'variants'}.`;save.hidden=mode==='view';save.textContent=mode==='edit'?'Save changes':'Add product';document.querySelector('#cancelProduct').textContent=mode==='view'?'Close':'Cancel';dialog.showModal()}
document.querySelectorAll('#addProduct,#introAddProduct').forEach(button=>button.addEventListener('click',()=>openProduct()));document.querySelector('#closeProductDialog').addEventListener('click',()=>dialog.close());document.querySelector('#cancelProduct').addEventListener('click',()=>dialog.close());
form.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));values.stock=Number(values.stock);if(editingIndex===null){products.unshift({icon:'□',variants:1,...values});showToast('Product added')}else{products[editingIndex]={...products[editingIndex],...values};showToast('Product updated')}dialog.close();currentView='all';document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view==='all';button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});render()});
const rowActions=document.querySelector('#rowActions');let actionIndex=null;rows.addEventListener('click',event=>{const button=event.target.closest('.customer-menu');if(!button)return;actionIndex=Number(button.dataset.index);const rect=button.getBoundingClientRect();rowActions.style.left=Math.max(8,rect.right-150)+'px';rowActions.style.top=Math.min(innerHeight-120,rect.bottom+5)+'px';rowActions.hidden=false});rowActions.addEventListener('click',event=>{const action=event.target.dataset.action;if(!action)return;rowActions.hidden=true;if(action==='view')openProduct('view',actionIndex);if(action==='edit')openProduct('edit',actionIndex);if(action==='archive'){products[actionIndex].status='Archived';render();showToast('Product archived')}});document.addEventListener('click',event=>{if(!rowActions.contains(event.target)&&!event.target.closest('.customer-menu'))rowActions.hidden=true});
const toast=document.querySelector('#customerToast');let toastTimer;function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
const sidebar=document.querySelector('#sidebar'),toggle=document.querySelector('.sidebar-toggle'),mobileMenu=document.querySelector('.customers-mobile-menu'),backdrop=document.querySelector('.drawer-backdrop'),mobile=matchMedia('(max-width:760px)');let collapsed=false;function sync(){const expanded=mobile.matches?sidebar.classList.contains('open'):!collapsed;toggle.setAttribute('aria-expanded',String(expanded));document.querySelector('.customers-app').classList.toggle('sidebar-collapsed',!mobile.matches&&collapsed)}toggle.addEventListener('click',()=>{if(mobile.matches){sidebar.classList.toggle('open');backdrop.hidden=!sidebar.classList.contains('open')}else collapsed=!collapsed;sync()});mobileMenu.addEventListener('click',()=>{sidebar.classList.add('open');backdrop.hidden=false;sync()});backdrop.addEventListener('click',()=>{sidebar.classList.remove('open');backdrop.hidden=true;sync()});mobile.addEventListener('change',()=>{sidebar.classList.remove('open');backdrop.hidden=true;sync()});sync();render();
