(() => {
 const revenue=[21000,24000,26000,22000,25000,28000,24000,18000,27000,25000,31000,28000,33000,22000,30000,28000,36000,44000,39000,42000,46000,41000,48000,52000];
 const expenses=[15000,18000,20000,18000,19000,21000,17000,21000,20000,18000,24000,21000,27000,31000,24000,20000,28000,26000,29000,32000,34000,30000,36000,38000];
 const data=revenue.map((value,i)=>({date:new Date(2025, i, 1),key:`${2025+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}`,revenue:value,expenses:expenses[i],profit:value-expenses[i]}));
 const chart=document.querySelector('#revenueChart'),svg=document.querySelector('#revenueSvg'),targets=document.querySelector('#revenueMonthTargets'),labels=document.querySelector('#revenueMonthLabels'),tooltip=document.querySelector('#revenueTooltip'),shell=document.querySelector('.revenue-chart-shell');
 const month=new Intl.DateTimeFormat('en',{month:'short'}),fullMonth=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'});
 let rows=[],start=12,end=17,active=-1;
 const W=720,H=210;
 function clear(){active=-1;tooltip.hidden=true;chart.classList.remove('has-active');svg.querySelector('.active-month-bg')?.setAttribute('visibility','hidden');svg.querySelectorAll('.month-bar').forEach(el=>el.classList.remove('is-active'));labels.querySelectorAll('span').forEach(el=>el.classList.remove('is-active'));targets.querySelectorAll('button').forEach(el=>el.removeAttribute('aria-describedby'))}
 function activate(i){const row=rows[i];if(!row)return;active=i;chart.classList.add('has-active');const bg=svg.querySelector('.active-month-bg');bg.setAttribute('x',i*W/rows.length+2);bg.setAttribute('visibility','visible');svg.querySelectorAll('.month-bar').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.index)===i));labels.querySelectorAll('span').forEach((el,index)=>el.classList.toggle('is-active',index===i));targets.querySelectorAll('button').forEach((el,index)=>{if(index===i)el.setAttribute('aria-describedby','revenueTooltip');else el.removeAttribute('aria-describedby')});tooltip.innerHTML=`<strong>${fullMonth.format(row.date)}</strong><div><span>Revenue</span><b>${formatNaira(row.revenue)}</b></div><div><span>Expenses</span><b>${formatNaira(row.expenses)}</b></div><div class="tooltip-profit"><span>Net Profit</span><b>${formatNaira(row.profit)}</b></div>`;tooltip.hidden=false;const rect=targets.children[i].getBoundingClientRect(),outer=shell.getBoundingClientRect();tooltip.style.left=Math.max(0,Math.min(outer.width-tooltip.offsetWidth,rect.left-outer.left+rect.width/2-tooltip.offsetWidth/2))+'px';tooltip.style.top='8px'}
 function render(){clear();rows=data.slice(start,end+1);const count=rows.length;chart.classList.toggle('year-view',count>6);chart.style.minWidth=count>12?`${count*52}px`:'';const maxValue=Math.max(...rows.flatMap(r=>[r.revenue,r.expenses,r.profit]));const step=Math.max(1000,Math.ceil(maxValue/4/5000)*5000);const high=step*4;const low=Math.min(...rows.map(r=>r.profit))<0?-step:0;const y=value=>H-(value-low)/(high-low)*H;const zero=y(0),slot=W/count,barWidth=Math.min(23,slot*.24),gap=5;
 let markup='';const ticks=[];for(let v=low;v<=high;v+=step){ticks.push(v);markup+=`<line class="chart-grid-line ${v===0?'chart-zero-line':''}" x1="0" x2="${W}" y1="${y(v)}" y2="${y(v)}"/>`}
 markup+=`<rect class="active-month-bg" x="0" y="0" width="${slot-4}" height="${H}" rx="5" visibility="hidden"/>`;
 rows.forEach((r,i)=>{const center=(i+.5)*slot;markup+=`<rect class="month-bar revenue-bar" data-index="${i}" x="${center-gap/2-barWidth}" y="${y(r.revenue)}" width="${barWidth}" height="${zero-y(r.revenue)}" rx="3"/><rect class="month-bar expense-bar" data-index="${i}" x="${center+gap/2}" y="${y(r.expenses)}" width="${barWidth}" height="${zero-y(r.expenses)}" rx="3"/>`});
 markup+=`<path class="profit-line" d="${rows.map((r,i)=>`${i?'L':'M'}${(i+.5)*slot} ${y(r.profit)}`).join(' ')}"/>`+rows.map((r,i)=>`<circle class="profit-dot" cx="${(i+.5)*slot}" cy="${y(r.profit)}" r="3"/>`).join('');svg.innerHTML=markup;
 document.querySelector('#revenueYAxis').innerHTML=ticks.map(v=>`<span style="top:${y(v)}px">${formatNaira(v,true)}</span>`).join('');labels.innerHTML=rows.map(r=>`<span class="month-label">${month.format(r.date)}${count>12?' '+String(r.date.getFullYear()).slice(2):''}</span>`).join('');targets.innerHTML=rows.map((r,i)=>`<button type="button" class="month-target" data-month="${i}" aria-label="${fullMonth.format(r.date)}: revenue ${formatNaira(r.revenue)}, expenses ${formatNaira(r.expenses)}, net profit ${formatNaira(r.profit)}"></button>`).join('');
 const total=rows.reduce((s,r)=>s+r.revenue,0),profit=rows.reduce((s,r)=>s+r.profit,0);document.querySelector('#chartTotal').innerHTML='<span class="currency-symbol">&#8358;</span>'+formatNaira(total,Math.abs(total)>10000000).replace('\u20a6','');document.querySelector('#chartTotal').title=formatNaira(total);document.querySelector('#chartTotal').setAttribute('aria-label',formatNaira(total));document.querySelector('#chartRange').textContent=fullMonth.format(rows[0].date)+' – '+fullMonth.format(rows.at(-1).date);document.querySelector('#profitSummary').innerHTML='Net profit <strong>'+formatNaira(profit,Math.abs(profit)>10000000)+'</strong>';document.querySelector('#profitSummary').title=formatNaira(profit);
 const previous=data.slice(Math.max(0,start-count),start);if(previous.length===count){const previousTotal=previous.reduce((s,r)=>s+r.revenue,0),change=(total/previousTotal-1)*100;document.querySelector('#revenueInsight').innerHTML=`Revenue <strong>${change>=0?'+':''}${change.toFixed(1)}%</strong> vs previous period`}else document.querySelector('#revenueInsight').textContent='Revenue overview · illustrative monthly data';
 // Keep the existing details arrow in sync with the chart selection.
 detailCopy.revenue=['Revenue',`<p>${fullMonth.format(rows[0].date)} – ${fullMonth.format(rows.at(-1).date)}</p><p>Revenue: <strong>${formatNaira(total)}</strong><br>Expenses: <strong>${formatNaira(total-profit)}</strong><br>Net Profit: <strong>${formatNaira(profit)}</strong></p>`];
 }
 for(const event of ['pointerover','focusin','click'])targets.addEventListener(event,e=>{const button=e.target.closest('[data-month]');if(button)activate(Number(button.dataset.month))});targets.addEventListener('pointerleave',()=>{if(!targets.contains(document.activeElement))clear()});targets.addEventListener('focusout',e=>{if(!targets.contains(e.relatedTarget))clear()});targets.addEventListener('keydown',e=>{if(e.key==='Escape'){clear();return}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const i=Number(e.target.dataset.month);targets.children[Math.max(0,Math.min(rows.length-1,i+(e.key==='ArrowRight'?1:-1)))].focus()});document.querySelector('.revenue-scroll').addEventListener('scroll',clear);window.addEventListener('resize',clear);
 document.querySelector('#revenuePeriod').addEventListener('change',e=>{const custom=e.target.value==='custom';document.querySelector('#customRevenueRange').hidden=!custom;if(custom){document.querySelector('#revenueFrom').focus();return}end=17;start=e.target.value==='12'?6:12;render()});
 document.querySelector('#customRevenueRange').addEventListener('submit',e=>{e.preventDefault();const from=document.querySelector('#revenueFrom').value,to=document.querySelector('#revenueTo').value;const a=data.findIndex(r=>r.key===from),b=data.findIndex(r=>r.key===to);if(a<0||b<0||a>b){document.querySelector('#rangeError').textContent='Choose a valid range from January 2025 to December 2026, with the start before the end.';return}document.querySelector('#rangeError').textContent='';start=a;end=b;render()});render();
})();
