(() => {
  const revenues=[21000,24000,26000,22000,25000,28000,24000,18000,27000,25000,31000,28000,33000,22000,30000,28000,36000,44000,39000,42000,46000,41000,48000,52000];
  const expenses=[15000,18000,20000,18000,19000,21000,17000,21000,20000,18000,24000,21000,27000,31000,24000,20000,28000,26000,29000,32000,34000,30000,36000,38000];
  const data=revenues.map((value,index)=>({date:new Date(2025,index,1),key:`${2025+Math.floor(index/12)}-${String(index%12+1).padStart(2,'0')}`,revenue:value,expenses:expenses[index],profit:value-expenses[index]}));
  const chart=document.querySelector('#revenueChart');
  if(!chart)return;
  const svg=document.querySelector('#revenueSvg'),targets=document.querySelector('#revenueMonthTargets'),labels=document.querySelector('#revenueMonthLabels'),tooltip=document.querySelector('#revenueTooltip'),shell=document.querySelector('.revenue-chart-shell');
  const month=new Intl.DateTimeFormat('en',{month:'short'}),fullMonth=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}),visible=new Set(['revenue','expenses','profit']);
  const W=720,H=210;
  let rows=[],start=12,end=17,compare=false;
  function clear(){tooltip.hidden=true;chart.classList.remove('has-active');svg.querySelector('.active-month-bg')?.setAttribute('visibility','hidden');svg.querySelectorAll('.month-bar').forEach(el=>el.classList.remove('is-active'));labels.querySelectorAll('span').forEach(el=>el.classList.remove('is-active'));targets.querySelectorAll('button').forEach(el=>el.removeAttribute('aria-describedby'))}
  function activate(index){const row=rows[index];if(!row)return;chart.classList.add('has-active');const bg=svg.querySelector('.active-month-bg');bg?.setAttribute('x',index*W/rows.length+2);bg?.setAttribute('visibility','visible');svg.querySelectorAll('.month-bar').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.index)===index));labels.querySelectorAll('span').forEach((el,i)=>el.classList.toggle('is-active',i===index));targets.querySelectorAll('button').forEach((el,i)=>i===index?el.setAttribute('aria-describedby','revenueTooltip'):el.removeAttribute('aria-describedby'));tooltip.innerHTML=`<strong>${fullMonth.format(row.date)}</strong><div><span>Revenue</span><b>${formatNaira(row.revenue)}</b></div><div><span>Expenses</span><b>${formatNaira(row.expenses)}</b></div><div class="tooltip-profit"><span>Net profit</span><b>${formatNaira(row.profit)}</b></div>`;tooltip.hidden=false;const rect=targets.children[index].getBoundingClientRect(),outer=shell.getBoundingClientRect();tooltip.style.left=Math.max(0,Math.min(outer.width-tooltip.offsetWidth,rect.left-outer.left+rect.width/2-tooltip.offsetWidth/2))+'px';tooltip.style.top='8px'}
  function render(){
    clear();rows=data.slice(start,end+1);const count=rows.length,previous=data.slice(Math.max(0,start-count),start);chart.classList.toggle('year-view',count>6);chart.style.minWidth=count>12?`${count*52}px`:'';
    const max=Math.max(...rows.flatMap(row=>[row.revenue,row.expenses,row.profit]),...previous.map(row=>compare?row.revenue:0)),step=Math.max(1000,Math.ceil(max/4/5000)*5000),high=step*4,low=Math.min(...rows.map(row=>row.profit))<0?-step:0,y=value=>H-(value-low)/(high-low)*H,zero=y(0),slot=W/count,barWidth=Math.min(23,slot*.24),gap=5,ticks=[];
    let markup='';for(let value=low;value<=high;value+=step){ticks.push(value);markup+=`<line class="chart-grid-line ${value===0?'chart-zero-line':''}" x1="0" x2="${W}" y1="${y(value)}" y2="${y(value)}"/>`}markup+=`<rect class="active-month-bg" x="0" y="0" width="${slot-4}" height="${H}" rx="5" visibility="hidden"/>`;
    rows.forEach((row,index)=>{const center=(index+.5)*slot;if(visible.has('revenue'))markup+=`<rect class="month-bar revenue-bar" data-index="${index}" x="${center-gap/2-barWidth}" y="${y(row.revenue)}" width="${barWidth}" height="${zero-y(row.revenue)}" rx="3"/>`;if(visible.has('expenses'))markup+=`<rect class="month-bar expense-bar" data-index="${index}" x="${center+gap/2}" y="${y(row.expenses)}" width="${barWidth}" height="${zero-y(row.expenses)}" rx="3"/>`});
    if(visible.has('profit')){markup+=`<path class="profit-line" d="${rows.map((row,index)=>`${index?'L':'M'}${(index+.5)*slot} ${y(row.profit)}`).join(' ')}"/>`;markup+=rows.map((row,index)=>`<circle class="profit-dot" cx="${(index+.5)*slot}" cy="${y(row.profit)}" r="3"/>`).join('')}
    if(compare&&previous.length===count)markup+=`<path class="comparison-line" d="${previous.map((row,index)=>`${index?'L':'M'}${(index+.5)*slot} ${y(row.revenue)}`).join(' ')}"/>`;svg.innerHTML=markup;
    document.querySelector('#revenueYAxis').innerHTML=ticks.map(value=>`<span style="top:${y(value)}px">${formatNaira(value,true)}</span>`).join('');labels.innerHTML=rows.map(row=>`<span class="month-label">${month.format(row.date)}${count>12?' '+String(row.date.getFullYear()).slice(2):''}</span>`).join('');targets.innerHTML=rows.map((row,index)=>`<button type="button" class="month-target" data-month="${index}" aria-label="${fullMonth.format(row.date)}: revenue ${formatNaira(row.revenue)}, expenses ${formatNaira(row.expenses)}, net profit ${formatNaira(row.profit)}"></button>`).join('');
    const total=rows.reduce((sum,row)=>sum+row.revenue,0),profit=rows.reduce((sum,row)=>sum+row.profit,0),totalEl=document.querySelector('#chartTotal'),rangeText=`${fullMonth.format(rows[0].date)} – ${fullMonth.format(rows.at(-1).date)}`;totalEl.innerHTML=`<span class="currency-symbol">&#8358;</span>${formatNaira(total,Math.abs(total)>10000000).replace('\u20a6','')}`;totalEl.title=formatNaira(total);totalEl.setAttribute('aria-label',formatNaira(total));document.querySelector('#chartRange').textContent=rangeText;document.querySelector('#dashboardDateLabel').textContent=rangeText;document.querySelector('#chartDescription').textContent=`Revenue from ${fullMonth.format(rows[0].date)} to ${fullMonth.format(rows.at(-1).date)} was ${formatNaira(total)}, with net profit of ${formatNaira(profit)}.`;
    detailCopy.revenue=['Revenue',`<p>${fullMonth.format(rows[0].date)} – ${fullMonth.format(rows.at(-1).date)}</p><p>Revenue: <strong>${formatNaira(total)}</strong><br>Expenses: <strong>${formatNaira(total-profit)}</strong><br>Net profit: <strong>${formatNaira(profit)}</strong></p>`];
  }
  for(const name of ['pointerover','focusin','click'])targets.addEventListener(name,event=>{const button=event.target.closest('[data-month]');if(button)activate(Number(button.dataset.month))});targets.addEventListener('pointerleave',()=>{if(!targets.contains(document.activeElement))clear()});targets.addEventListener('focusout',event=>{if(!targets.contains(event.relatedTarget))clear()});targets.addEventListener('keydown',event=>{if(event.key==='Escape')return clear();if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const index=Number(event.target.dataset.month);targets.children[Math.max(0,Math.min(rows.length-1,index+(event.key==='ArrowRight'?1:-1)))].focus()});document.querySelector('.revenue-scroll').addEventListener('scroll',clear);window.addEventListener('resize',clear);
  document.querySelectorAll('[data-period]').forEach(button=>button.addEventListener('click',()=>{const count=Number(button.dataset.period);end=17;start=end-count+1;document.querySelectorAll('[data-period]').forEach(item=>{const selected=item===button;item.classList.toggle('active',selected);item.setAttribute('aria-pressed',String(selected))});document.querySelector('#customRevenueRange').hidden=true;document.querySelector('#customRangeToggle').setAttribute('aria-expanded','false');render()}));
  document.querySelector('#customRangeToggle').addEventListener('click',event=>{const form=document.querySelector('#customRevenueRange'),opening=form.hidden;form.hidden=!opening;event.currentTarget.setAttribute('aria-expanded',String(opening));if(opening)document.querySelector('#revenueFrom').focus()});document.querySelector('#compareRevenue').addEventListener('click',event=>{compare=!compare;event.currentTarget.setAttribute('aria-pressed',String(compare));event.currentTarget.classList.toggle('active',compare);render()});
  document.querySelectorAll('[data-series]').forEach(button=>button.addEventListener('click',()=>{const series=button.dataset.series;if(visible.has(series)&&visible.size>1)visible.delete(series);else visible.add(series);button.setAttribute('aria-pressed',String(visible.has(series)));render()}));
  document.querySelector('#customRevenueRange').addEventListener('submit',event=>{event.preventDefault();const first=data.findIndex(row=>row.key===document.querySelector('#revenueFrom').value),last=data.findIndex(row=>row.key===document.querySelector('#revenueTo').value);if(first<0||last<0||first>last){document.querySelector('#rangeError').textContent='Choose a valid range from January 2025 to December 2026, with the start before the end.';return}document.querySelector('#rangeError').textContent='';start=first;end=last;document.querySelectorAll('[data-period]').forEach(item=>{item.classList.remove('active');item.setAttribute('aria-pressed','false')});document.querySelector('#customRevenueRange').hidden=true;document.querySelector('#customRangeToggle').setAttribute('aria-expanded','false');render()});
  render();
})();
