const periods={sep:{sales:'NGN 24.8m',orders:'386',units:'1,248',stock:'12',bars:[5.2,6.1,6.4,7.1],previous:'August',growth:'+14.8%',dispatch:24,production:472,ready:328},aug:{sales:'NGN 21.6m',orders:'343',units:'1,153',stock:'9',bars:[4.8,5.1,5.5,6.2],previous:'July',growth:'+7.5%',dispatch:18,production:560,ready:240}};
const dialog=document.querySelector('#details');
function show(title,body){document.querySelector('#detailTitle').textContent=title;document.querySelector('#detailBody').textContent=body;dialog.showModal()}
document.querySelector('#closeDetails').addEventListener('click',()=>dialog.close());
function render(){const d=periods[document.querySelector('#period').value];const metrics=[['Net sales',d.sales,d.growth,'up'],['Orders fulfilled',d.orders,'Delivered','neutral'],['Units sold',d.units,'All collections','neutral'],['Low-stock variants',d.stock,'Reorder','alert']];document.querySelector('#metrics').innerHTML=metrics.map(([name,value,change,status],i)=>`<article class="metric ${i===0?'featured':''}"><p>${name}</p><button class="arrow" aria-label="View ${name}" data-index="${i}">&#8599;</button><strong>${value}<small class="${status}">${change}</small></strong><small>${i===0?'Compared with '+d.previous:i===3?'Size / colour SKUs below 10 units':'Selected reporting month'}</small></article>`).join('');document.querySelector('#bars').innerHTML=d.bars.map((v,i)=>`<div class="bar-item" tabindex="0" role="img" aria-label="Week ${i+1}: NGN ${v} million"><b>NGN ${v}m</b><i style="height:${v*10}%"></i><span>WEEK ${i+1}</span></div>`).join('');const counters=document.querySelectorAll('.counter');counters[0].textContent=d.dispatch;counters[1].textContent=d.production;document.querySelector('.wide-stat p').innerHTML=`${d.dispatch} paid orders <em>await dispatch.</em>`;document.querySelector('.customers p').innerHTML=`${d.ready} of 800 A/W garments <em>are ready.</em>`;document.querySelector('#metrics').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.index);show(metrics[i][0],[`${d.sales} after discounts and returns. Weekly totals sum to the monthly net sales.`,`${d.orders} customer orders delivered in the selected month.`,`${d.units} garments and accessories sold across all collections.`,`${d.stock} size and colour variants have fewer than 10 available units. Review replenishment before the next drop.`][i])}));}
const toggle=document.querySelector('#themeToggle');let saved;try{saved=localStorage.getItem('wave-theme')}catch{}document.body.classList.toggle('light',saved==='light');function themeLabel(){const light=document.body.classList.contains('light');toggle.setAttribute('aria-pressed',String(light));toggle.setAttribute('aria-label',`Switch to ${light?'dark':'light'} mode`);toggle.title=toggle.getAttribute('aria-label')};themeLabel();toggle.addEventListener('click',()=>{document.body.classList.toggle('light');themeLabel();try{localStorage.setItem('wave-theme',document.body.classList.contains('light')?'light':'dark')}catch{}});
document.querySelector('#period').addEventListener('change',render);
document.querySelector('#search').addEventListener('input',event=>{const q=event.target.value.toLowerCase();document.querySelectorAll('.category-body li').forEach(li=>li.hidden=!li.textContent.toLowerCase().includes(q));let empty=document.querySelector('#categoryEmpty');if(!empty){empty=document.createElement('p');empty.id='categoryEmpty';empty.textContent='No matching categories.';document.querySelector('.category-body').append(empty)}empty.hidden=[...document.querySelectorAll('.category-body li')].some(li=>!li.hidden)});
const nav=['Overview','Collections','Production','Customers','Inventory','Reports'];document.querySelectorAll('.sidebar nav a').forEach((a,i)=>{a.setAttribute('href','#');a.setAttribute('aria-label',nav[i]);a.title=nav[i];a.addEventListener('click',e=>{e.preventDefault();if(i===0)return;show(nav[i],['','Autumn / Winter 2026 launches on 28 September. Other collections: The Linen Edit, Everyday Essentials, Evening in Silk.',`${periods[document.querySelector('#period').value].production} garments in production for the 800-unit Autumn / Winter launch.`,'Review customer order history, preferred sizes, and fulfilment requests. Illustrative dashboard data.',`${periods[document.querySelector('#period').value].stock} variants need replenishment. Example: Linen set / Sand / M, 4 available.`,'Switch the reporting month to compare sales, units sold, and fulfilment.'][i])})});
document.querySelector('.collapse').setAttribute('aria-label','About workspace');document.querySelector('.collapse').addEventListener('click',()=>show('Atelier workspace','Fashion operations overview. Use the sidebar to explore collections, production, customers and inventory.'));
document.querySelector('.logout').setAttribute('aria-label','Demo account');document.querySelector('.logout').addEventListener('click',()=>show('Demo account','No account is signed in to this local design concept.'));
document.querySelector('[aria-label="Notifications"]').addEventListener('click',()=>show('Studio alerts','Sample review at 2 pm. Courier pickup at 3 pm. Check low-stock variants before the next launch.'));
document.querySelectorAll('.card-head button').forEach((b,i)=>{b.setAttribute('aria-label',i?'Category breakdown':'Sales breakdown');b.addEventListener('click',()=>show(i?'Category breakdown':'Weekly net sales',i?'Share of units sold: dresses 35%, co-ord sets 25%, trousers 20%, tops 12%, accessories 8%. The same illustrative mix is used for both months.':'The four bars represent weekly net sales for the selected month in millions of Nigerian naira. Hover or focus a bar for its value.'))});
document.querySelector('.wide-stat>button').setAttribute('aria-label','Dispatch details');document.querySelector('.wide-stat>button').addEventListener('click',()=>show('Dispatch queue',`${periods[document.querySelector('#period').value].dispatch} paid orders await dispatch. Example: AT-1048, Linen set, Sand / M, packing.`));render();
