const paths={panel:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M15 3v18"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',box:'<path d="m12 2 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V7m-9 5v10M7 5l10 5"/>',truck:'<path d="M3 5h11v12H3V5Zm11 5h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v3"/>',store:'<path d="m4 3-2 6a3 3 0 0 0 5 2 3 3 0 0 0 5 0 3 3 0 0 0 5 0 3 3 0 0 0 5-2l-2-6H4Zm0 10v8h16v-8M9 21v-6h6v6"/>',chart:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 16v-4m5 4V7m5 9v-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4h.01"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',lock:'<rect x="5" y="10" width="14" height="12" rx="5"/><path d="M8 10V6a4 4 0 0 1 8 0m-4 13v-3"/>',crown:'<path d="m3 6 5 5 4-8 4 8 5-5-2 15H5L3 6Zm3 11h12"/>',search:'<circle cx="10" cy="10" r="8"/><path d="m16 16 6 6"/>',sliders:'<path d="M6 2v7m0 6v7M18 2v3m0 6v11"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="8" r="3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9m-9 12h6"/>',mail:'<rect x="3" y="5" width="18" height="15" rx="4"/><path d="m4 8 8 5 8-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',cart:'<path d="M2 3h3l3 12h11l3-9H6M8 15l-1 3h12"/><circle cx="9" cy="21" r="1.5"/><circle cx="18" cy="21" r="1.5"/>',return:'<path d="M4 9V4h5M4 4l5 5m-5 3v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-5M9 14h7m-3-3 3 3-3 3"/>',network:'<circle cx="12" cy="4" r="2"/><circle cx="4" cy="19" r="3"/><circle cx="12" cy="17" r="3"/><circle cx="20" cy="19" r="3"/><path d="M12 6v8m-8 2v-5h16v5"/>',arrow:'<path d="M6 18 18 6M7 6h11v11"/>',edit:'<path d="m4 16 12-12 4 4-12 12H4v-4Zm9-9 4 4M3 22h18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15m-8 4v7m4-7v7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="3" y="12" width="5" height="9" rx="2"/><rect x="16" y="12" width="5" height="9" rx="2"/>',helmet:'<path d="M3 14a9 9 0 0 1 18 0v5H8l-5-5Zm0 0h18M8 19l2 3h8v-3M7 5l3 7"/>',shirt:'<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4a4 4 0 0 1-8 0Z"/>',glasses:'<path d="M2 9h7l2 2h2l2-2h7l-2 9h-4l-3-6h-2l-3 6H4L2 9Zm0 0 2-5m18 5-2-5"/>',bottle:'<path d="M10 2h4v5l3 4v11H7V11l3-4V2Zm-1 12h6M10 5h4"/>',bag:'<rect x="5" y="7" width="14" height="15" rx="4"/><path d="M9 7V4a3 3 0 0 1 6 0v3M8 13h8v6H8v-6M5 9l-2 9m16-9 2 9"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.box}</svg>`}
paths.grid=paths.chart;
paths.layers='<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>';
paths.wallet='<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 8V5l14-3v3m4 7h-6v5h6m-3-2.5h.01"/>';
paths.chevron='<path d="m6 9 6 6 6-6"/>';
paths.calendar='<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3"/>';
paths.download='<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>';
paths.left='<path d="m15 6-6 6 6 6"/>';
paths.right='<path d="m9 6 6 6-6 6"/>';
paths.more='<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>';
document.querySelectorAll('[data-icon]').forEach(el=>el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon)));
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base={sep:{month:8,label:'September 2026',received:8500000,spent:6222000,opening:13422000,outstanding:3291300,invoices:12,prevReceived:8000000,prevSpent:5800000,prevBalance:14000000},aug:{month:7,label:'August 2026',received:8000000,spent:5800000,opening:11800000,outstanding:2875000,invoices:10,prevReceived:8100000,prevSpent:6000000,prevBalance:13100000}};
const sampleRows=[['Tunde Adewale','Bespoke suit deposit','Bespoke','in',280000,'bank','Completed'],['Lagos Textile Co.','Italian wool fabric','Materials','out',420000,'bank','Completed'],['Kola Williams','Agbada final payment','Bespoke','in',225000,'bank','Completed'],['Studio payroll','September production team','Payroll','out',950000,'bank','Completed'],['Ada Okafor','Kaftan order deposit','Ready-to-wear','in',195000,'cash','Pending'],['Swift Logistics','Client order dispatch','Logistics','out',65000,'bank','Completed'],['Bola Martins','Leather shoes','Accessories','in',85000,'cash','Completed'],['Deji Balogun','Suit balance','Bespoke','in',180000,'bank','Completed']];
let entries=['sep','aug'].flatMap((period,pi)=>sampleRows.map((r,i)=>({id:`TX-${pi?2100:2200+i}`,period,date:`2026-${pi?'08':'09'}-${String(13-i).padStart(2,'0')}`,party:r[0],description:r[1].replace('September',pi?'August':'September'),category:r[2],direction:r[3],amount:r[4],account:r[5],status:r[6],added:false}))).map((e,i)=>({...e,id:'TX-'+(2200+i)}));let nextId=2300;
const splits=[{name:'Materials',share:.4,color:'#38bdf8'},{name:'Payroll',share:.28,color:'#86cef4'},{name:'Studio',share:.16,color:'#b4d7ed'},{name:'Logistics',share:.1,color:'#839db5'},{name:'Other',share:.06,color:'#d9e5f0'}];
const targets=[{name:'Autumn / Winter 26',saved:3200000,target:5000000,note:'Launch · 28 Sep'},{name:'The Linen Edit',saved:1750000,target:2500000,note:'Fabric sourcing'},{name:'Resort Capsule',saved:900000,target:3000000,note:'Sampling & development'}];
let activeMonth=5;const money=v=>formatNaira(v,Math.abs(v)>10000000);const monthKey=()=>document.querySelector('#period').value;
function totals(key=monthKey()){const b=base[key],newRows=entries.filter(e=>e.added&&e.period===key&&e.status==='Completed'),received=b.received+newRows.filter(e=>e.direction==='in').reduce((s,e)=>s+e.amount,0),spent=b.spent+newRows.filter(e=>e.direction==='out').reduce((s,e)=>s+e.amount,0);return {...b,received,spent,balance:b.opening+received-spent}}
function percent(current,previous){const p=(current/previous-1)*100;return (p>=0?'+':'')+p.toFixed(1)+'%'}
function filteredEntries(){const key=monthKey(),q=document.querySelector('#search').value.toLowerCase().trim(),type=document.querySelector('#typeFilter').value;return entries.filter(e=>e.period===key&&(type==='all'||e.direction===type)&&(e.party+' '+e.description+' '+e.id+' '+e.category).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||Number(b.id.slice(3))-Number(a.id.slice(3)))}
function renderTransactions(){const list=filteredEntries();document.querySelector('#transactionRows').innerHTML=list.slice(0,5).map(e=>`<tr><td>${new Date(e.date+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</td><td><div class="transaction-name"><span class="transaction-symbol">${icon(e.direction==='in'?'bag':'wallet')}</span><div><strong>${esc(e.party)}</strong><small>${esc(e.description)}</small></div></div></td><td>${esc(e.category)}</td><td class="amount ${e.direction==='in'?'incoming':''}">${e.direction==='in'?'+':'−'}${formatNaira(e.amount)}</td><td><span class="status ${e.status==='Completed'?'completed':'pending'}">${e.status}</span></td><td><button class="row-action" data-entry="${e.id}" aria-label="View ${e.id} details">${icon('more')}</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty-row">No transactions found. Try another search or filter.</td></tr>';document.querySelector('#transactionCount').textContent=`Showing ${Math.min(list.length,5)} of ${list.length} transactions`}
const drawer=document.querySelector('#detailDrawer'),action=document.querySelector('#actionDialog');function showDrawer(title,html){document.querySelector('#drawerTitle').textContent=title;document.querySelector('#drawerContent').innerHTML=html;if(!drawer.open)drawer.showModal()}function showAction(title,html){document.querySelector('#actionTitle').textContent=title;document.querySelector('#actionContent').innerHTML=html;action.showModal()}document.querySelector('#closeDrawer').onclick=()=>drawer.close();document.querySelector('#closeAction').onclick=()=>action.close();let toastTimer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function entryDetails(id){const e=entries.find(x=>x.id===id);showDrawer(e.id,`<span class="status ${e.status==='Completed'?'completed':'pending'}">${e.status}</span><div class="entry-amount">${e.direction==='in'?'+':'−'}${formatNaira(e.amount)}</div><div class="detail-grid"><div><small>${e.direction==='in'?'Client':'Payee'}</small><strong>${esc(e.party)}</strong></div><div><small>Date</small><strong>${e.date}</strong></div><div><small>Category</small><strong>${esc(e.category)}</strong></div><div><small>Account</small><strong>${e.account==='bank'?'Bank account':'Studio cash'}</strong></div></div><div class="drawer-section" style="margin-top:28px"><h3>Description</h3><p>${esc(e.description)}</p></div>${e.status==='Pending'?'<p class="pending-note">This payment has not settled and is excluded from cash-flow totals.</p>':''}<p class="form-hint">Illustrative record. No real payment has been sent or received.</p>`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-entry]');if(b)entryDetails(b.dataset.entry)});
document.querySelector('#seeAll').onclick=()=>showDrawer('Transaction history','<p>Current search and type filters are applied.</p><ul class="drawer-transaction-list">'+filteredEntries().map(e=>`<li><button data-entry="${e.id}"><span><strong>${esc(e.party)}</strong><small>${e.date} · ${e.id}</small></span><b>${e.direction==='in'?'+':'−'}${formatNaira(e.amount)}</b></button></li>`).join('')+'</ul>');
function expenseAmounts(){const total=totals().spent;let remaining=total;return splits.map((s,i)=>{const amount=i===splits.length-1?remaining:Math.round(total*s.share);remaining-=amount;return {...s,amount}})}
function expenseDetail(index){const rows=expenseAmounts();showDrawer(index===undefined?'Operating expenses':rows[index].name,`<p>${totals().label} · Illustrative allocation</p><div class="entry-amount">${formatNaira(index===undefined?totals().spent:rows[index].amount)}</div><div class="batch-list">${(index===undefined?rows:[rows[index]]).map(s=>`<div><span>${s.name} · ${Math.round(s.share*100)}%</span><strong>${formatNaira(s.amount)}</strong></div>`).join('')}</div><p class="form-hint">This preview allocates expenses using fixed category shares. A connected ERP would calculate the mix from its ledger.</p>`)}
function renderExpenses(){const rows=expenseAmounts(),circ=2*Math.PI*72;let offset=0;document.querySelector('#spendLegend').innerHTML=rows.map((s,i)=>`<button class="spend-item" data-expense="${i}" style="--color:${s.color}"><i></i>${s.name}<span>${Math.round(s.share*100)}%</span></button>`).join('');document.querySelector('#spendSvg').setAttribute('aria-label','Expense mix: '+rows.map(s=>s.name+' '+Math.round(s.share*100)+'%').join(', '));document.querySelector('#spendSvg').innerHTML=rows.map((s,i)=>{const len=s.share*circ,gap=9,markup=`<circle class="ring-segment" style="--color:${s.color}" cx="90" cy="90" r="72" transform="rotate(-90 90 90)" stroke-dasharray="${Math.max(1,len-gap)} ${circ}" stroke-dashoffset="${-offset}" tabindex="0" role="button" data-expense="${i}" aria-label="${s.name}: ${formatNaira(s.amount)}"><title>${s.name}: ${formatNaira(s.amount)}</title></circle>`;offset+=len;return markup}).join('');document.querySelector('#spendTotal').textContent=formatNaira(totals().spent,true);document.querySelector('#spendTotal').title=formatNaira(totals().spent);document.querySelector('#spendNote').textContent='Materials account for 40% of your operating expenses this month.'}
document.addEventListener('click',e=>{const el=e.target.closest('[data-expense]');if(el)expenseDetail(Number(el.dataset.expense))});document.querySelector('#spendSvg').addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.dataset.expense!==undefined){e.preventDefault();expenseDetail(Number(e.target.dataset.expense))}});document.querySelector('#expenseDetails').onclick=()=>expenseDetail();
function renderGoals(){document.querySelector('#goals').innerHTML=targets.map((t,i)=>`<button class="goal" data-goal="${i}" aria-label="${t.name}: ${Math.round(t.saved/t.target*100)} percent funded"><div class="goal-top"><strong>${t.name}</strong><span>${formatNaira(t.target,true)}</span></div><div class="goal-track"><span style="width:${t.saved/t.target*100}%"></span></div><div class="goal-footer"><span>${Math.round(t.saved/t.target*100)}% funded</span><span>${t.note}</span></div></button>`).join('')}
function goalDetails(i){const rows=i===undefined?targets:[targets[i]];showDrawer(i===undefined?'Collection targets':rows[0].name,rows.map(t=>`<div class="drawer-section"><h3>${t.name}</h3><div class="detail-grid"><div><small>Reserved</small><strong>${formatNaira(t.saved)}</strong></div><div><small>Target</small><strong>${formatNaira(t.target)}</strong></div></div><p>${formatNaira(t.target-t.saved)} remaining · ${Math.round(t.saved/t.target*100)}% funded.</p></div>`).join('')+'<p class="form-hint">These are planning targets; no funds are transferred by this preview.</p>')}
document.querySelector('#goals').onclick=e=>{const b=e.target.closest('[data-goal]');if(b)goalDetails(Number(b.dataset.goal))};document.querySelector('#goalDetails').onclick=()=>goalDetails();
const flowIncome=[5.9,6.1,7.2,7,8.1,8,8.5],flowExpense=[4.1,4.4,5.3,5.5,6,5.8,6.222];let flowRows=[];
function hideChartTip(){document.querySelector('#cashTooltip').hidden=true;document.querySelector('.cash-plot').classList.remove('is-focused');document.querySelectorAll('.cash-bar').forEach(el=>el.classList.remove('is-active'));document.querySelector('.month-highlight')?.setAttribute('visibility','hidden');document.querySelectorAll('[data-month]').forEach(el=>el.removeAttribute('aria-describedby'))}
function chartTip(button){const i=Number(button.dataset.month),r=flowRows[i],tip=document.querySelector('#cashTooltip');hideChartTip();document.querySelector('.cash-plot').classList.add('is-focused');document.querySelectorAll('.cash-bar').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.index)===i));const bg=document.querySelector('.month-highlight');bg.setAttribute('x',i*120+4);bg.setAttribute('visibility','visible');button.setAttribute('aria-describedby','cashTooltip');tip.innerHTML=`<strong>${r.label} 2026</strong><div><span>Money in</span><b>${formatNaira(r.income)}</b></div><div><span>Money out</span><b>${formatNaira(r.expense)}</b></div><div class="tooltip-net"><span>Net flow</span><b>${formatNaira(r.income-r.expense)}</b></div>`;tip.hidden=false;const rect=button.getBoundingClientRect(),wrap=document.querySelector('.cash-chart-wrap').getBoundingClientRect();tip.style.left=Math.max(0,Math.min(wrap.width-tip.offsetWidth,rect.left-wrap.left+rect.width/2-tip.offsetWidth/2))+'px'}
function renderChart(){const key=monthKey(),account=document.querySelector('#channel').value,mult=account==='bank'?.85:account==='cash'?.15:1,offset=key==='sep'?1:0,d=totals();flowRows=Array.from({length:6},(_,i)=>{const j=i+offset,month=2+j;return {label:new Date(2026,month,1).toLocaleDateString('en',{month:'short'}),income:Math.round((i===5?base[key].received:flowIncome[j]*1e6)*mult)+(i===5?entries.filter(e=>e.added&&e.period===key&&e.status==='Completed'&&e.direction==='in'&&(account==='all'||e.account===account)).reduce((s,e)=>s+e.amount,0):0),expense:Math.round((i===5?base[key].spent:flowExpense[j]*1e6)*mult)}});const max=Math.ceil(Math.max(...flowRows.flatMap(r=>[r.income,r.expense]))/2e6)*2e6,y=v=>190-v/max*180;let html=Array.from({length:5},(_,i)=>`<line class="cash-grid-line" x1="0" x2="720" y1="${y(max*i/4)}" y2="${y(max*i/4)}"/>`).join('')+'<rect class="month-highlight" x="0" y="0" width="112" height="190" rx="5" visibility="hidden"/>';html+=flowRows.map((r,i)=>`<rect class="cash-bar" data-index="${i}" x="${i*120+33}" y="${y(r.income)}" width="24" height="${190-y(r.income)}" rx="5"/><rect class="cash-bar outgoing" data-index="${i}" x="${i*120+63}" y="${y(r.expense)}" width="24" height="${190-y(r.expense)}" rx="5"/>`).join('');document.querySelector('#cashSvg').innerHTML=html;document.querySelector('#cashAxis').innerHTML=Array.from({length:5},(_,i)=>`<span style="top:${y(max*i/4)}px">${(max*i/4/1e6).toLocaleString('en',{maximumFractionDigits:1})}m</span>`).join('');document.querySelector('#cashMonths').innerHTML=flowRows.map(r=>'<span>'+r.label+'</span>').join('');document.querySelector('#cashTargets').innerHTML=flowRows.map((r,i)=>`<button data-month="${i}" aria-label="${r.label}: money in ${formatNaira(r.income)}, money out ${formatNaira(r.expense)}"></button>`).join('');document.querySelector('#chartPeriod').textContent=flowRows[0].label+' – '+flowRows.at(-1).label+' 2026';document.querySelector('#netFlow').innerHTML='Net flow <b>'+formatNaira(flowRows.reduce((s,r)=>s+r.income-r.expense,0),true)+'</b>';hideChartTip()}
const chartTargets=document.querySelector('#cashTargets');for(const type of ['pointerover','focusin','click'])chartTargets.addEventListener(type,e=>{const b=e.target.closest('[data-month]');if(b)chartTip(b)});chartTargets.addEventListener('pointerleave',()=>{if(!chartTargets.contains(document.activeElement))hideChartTip()});chartTargets.addEventListener('focusout',e=>{if(!chartTargets.contains(e.relatedTarget))hideChartTip()});chartTargets.addEventListener('keydown',e=>{if(e.key==='Escape')hideChartTip();if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();chartTargets.children[Math.max(0,Math.min(5,Number(e.target.dataset.month)+(e.key==='ArrowRight'?1:-1)))].focus()}});document.querySelector('.cash-scroll').addEventListener('scroll',hideChartTip);window.addEventListener('resize',hideChartTip);
function render(){const t=totals();for(const [id,value]of [['balance',t.balance],['income',t.received],['expenses',t.spent],['outstanding',t.outstanding]]){const el=document.getElementById(id);el.textContent=money(value);el.title=formatNaira(value);el.setAttribute('aria-label',formatNaira(value))}document.querySelector('#balanceTrend').textContent=percent(t.balance,t.prevBalance);document.querySelector('#incomeTrend').textContent=percent(t.received,t.prevReceived);document.querySelector('#expenseTrend').textContent=percent(t.spent,t.prevSpent);document.querySelector('#invoiceCount').textContent=t.invoices+' open invoices';renderTransactions();renderExpenses();renderChart();fitFigures()}
document.querySelector('#period').onchange=render;document.querySelector('#channel').onchange=renderChart;document.querySelector('#search').addEventListener('input',renderTransactions);document.querySelector('#typeFilter').onchange=renderTransactions;
document.querySelector('#recordPayment').onclick=()=>{showDrawer('Record payment','<p>Log a client payment already received. This creates a record; it does not charge a customer.</p><form id="paymentForm"><label>Client name<input name="party" required maxlength="60" placeholder="e.g. Tunde Adewale"></label><label>Amount (NGN)<input name="amount" type="number" min="0.01" max="1000000000" step="0.01" required placeholder="0.00"></label><div class="form-row"><label>Category<select name="category"><option>Bespoke</option><option>Ready-to-wear</option><option>Accessories</option></select></label><label>Account<select name="account"><option value="bank">Bank account</option><option value="cash">Studio cash</option></select></label></div><label>Payment date<input name="date" type="date" min="2026-08-01" max="2026-09-30" required value="'+(monthKey()==='sep'?'2026-09-14':'2026-08-14')+'"></label><label>Reference / description<input name="description" maxlength="100" placeholder="e.g. Suit balance" required></label><p class="form-hint">Supports August and September 2026 in this demo. Added payments update the selected month. Changes reset on reload.</p><p id="paymentError" class="inline-error" role="status"></p><div class="form-actions"><button type="button" class="secondary" id="cancelPayment">Cancel</button><button class="primary">Save payment</button></div></form>');document.querySelector('#cancelPayment').onclick=()=>drawer.close();document.querySelector('#paymentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),party=d.get('party').trim(),description=d.get('description').trim();if(!party||!description){document.querySelector('#paymentError').textContent='Enter a client name and description.';return}const period=d.get('date').slice(5,7)==='09'?'sep':'aug';entries.unshift({id:'TX-'+nextId++,period,date:d.get('date'),party,description,category:d.get('category'),amount:Number(d.get('amount')),account:d.get('account'),direction:'in',status:'Completed',added:true});document.querySelector('#period').value=period;document.querySelector('#search').value='';document.querySelector('#typeFilter').value='all';render();drawer.close();toast('Payment recorded in this preview')}};
function csvCell(v){let s=String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}document.querySelector('#export').onclick=()=>{const t=totals(),rows=[['DK Studio report',t.label],['Available balance (NGN)',t.balance],['Payments received (NGN)',t.received],['Operating expenses (NGN)',t.spent],['Outstanding invoices (NGN)',t.outstanding],[],['Filtered transactions'],['Reference','Date','Party','Type','Amount (NGN)','Account','Status'],...filteredEntries().map(e=>[e.id,e.date,e.party,e.direction,e.amount,e.account,e.status])],blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dk-studio-'+monthKey()+'-2026.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Report exported')};
const app=document.querySelector('.app'),sidebar=document.querySelector('#sidebar'),mobile=matchMedia('(max-width:700px)'),tablet=matchMedia('(min-width:701px) and (max-width:850px)'),collapse=document.querySelector('#collapse'),menuButton=document.querySelector('#mobileMenu'),backdrop=document.querySelector('#navBackdrop');let collapsed=false;
function menu(open){sidebar.classList.toggle('open',open);sidebar.inert=mobile.matches&&!open;document.querySelector('#main').inert=open;backdrop.hidden=!open;document.body.classList.toggle('nav-open',open);menuButton.setAttribute('aria-expanded',String(open));collapse.setAttribute('aria-label',mobile.matches?'Close navigation':collapsed?'Expand sidebar':'Collapse sidebar');if(open){sidebar.setAttribute('role','dialog');sidebar.setAttribute('aria-modal','true');sidebar.setAttribute('aria-label','Navigation');collapse.focus()}else{sidebar.removeAttribute('role');sidebar.removeAttribute('aria-modal');sidebar.removeAttribute('aria-label')}}menuButton.onclick=()=>menu(true);collapse.onclick=()=>{if(mobile.matches){menu(false);menuButton.focus()}else{collapsed=!collapsed;app.classList.toggle('collapsed',collapsed);collapse.setAttribute('aria-expanded',String(!collapsed));collapse.setAttribute('aria-label',collapsed?'Expand sidebar':'Collapse sidebar');hideNavTip()}};backdrop.onclick=()=>{menu(false);menuButton.focus()};mobile.addEventListener('change',()=>menu(false));sidebar.addEventListener('keydown',e=>{if(!mobile.matches||!sidebar.classList.contains('open'))return;if(e.key==='Escape'){menu(false);menuButton.focus()}if(e.key==='Tab'){const f=[...sidebar.querySelectorAll('a,button')].filter(x=>x.getClientRects().length);if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});
const tip=document.querySelector('#navTooltip');let owner;function hideNavTip(){tip.hidden=true;owner?.removeAttribute('aria-describedby');owner=null}function showNavTip(a){if(mobile.matches||!(collapsed||tablet.matches))return;hideNavTip();owner=a;tip.textContent=a.getAttribute('aria-label');tip.hidden=false;a.setAttribute('aria-describedby','navTooltip');const r=a.getBoundingClientRect();tip.style.left=r.right+12+'px';tip.style.top=r.top+6+'px'}
const info={production:['Production overview','<p>Autumn / Winter 2026: 328 of 800 units ready.</p><ul><li>400 units in sewing and finishing</li><li>72 units in cutting</li></ul><p>Launch: 28 September.</p>'],inventory:['Stock attention','<p>12 variants are below the 10-unit reorder point.</p><ul><li>Sand kaftan, M: 4 available</li><li>Charcoal suit, L: 6 available</li><li>Black shoes, 43: 3 available</li></ul>'],clients:['Client book','<p>Manage measurements, preferred styles, purchase history, and outstanding payments.</p><p>Example: Tunde Adewale · Bespoke suit · Deposit received.</p>'],reports:['Reports','<p>The top period control switches financial summaries and recent transactions. Account filters affect only the cash-flow chart. Historical demo cash flow is allocated 85% to bank and 15% to studio cash; new payments use the account recorded.</p><p>Export downloads a CSV with monthly totals and the filtered transaction list.</p>'],settings:['Workspace settings','<p>DK Fashion House · NGN</p><p>This local preview does not persist settings or records.</p>'],help:['Help & resources','<p>Record a payment, filter transactions, open transaction details, or export a report.</p><p>Figures are illustrative. Monthly totals include more records than the recent list. Expenses use a fixed demo allocation; collection goals are separate planning targets.</p>']};document.querySelectorAll('.sidebar nav a').forEach(a=>{a.setAttribute('aria-label',a.querySelector('.nav-copy').textContent);a.addEventListener('mouseenter',()=>showNavTip(a));a.addEventListener('focus',()=>showNavTip(a));a.addEventListener('mouseleave',hideNavTip);a.addEventListener('blur',hideNavTip);a.onclick=e=>{hideNavTip();const key=a.getAttribute('href').slice(1);if(mobile.matches)menu(false);if(['overview','orders','collections','finance'].includes(key))return;e.preventDefault();showDrawer(...info[key])}});
function account(){showDrawer('Deji & Kola','<p>Brand owners · DK Fashion House</p><p>This is an illustrative workspace with no connected bank, payment provider, or signed-in account.</p>')}document.querySelector('#profile').onclick=account;document.querySelector('#account').onclick=account;document.querySelector('#notifications').onclick=()=>showDrawer('Studio notifications','<ul class="drawer-orders"><li><strong>Open invoices</strong><br>Review client balances before dispatch.</li><li><strong>Autumn / Winter launch</strong><br>28 September · 64% of funding reserved.</li><li><strong>Pending payment</strong><br>Ada Okafor: awaiting settlement.</li></ul>');window.addEventListener('resize',hideNavTip);window.addEventListener('scroll',hideNavTip,true);document.addEventListener('keydown',e=>{if(e.key==='Escape')hideNavTip()});menu(false);renderGoals();render();

function fitFigures(){
 const figures=[...document.querySelectorAll('.kpi>strong')];
 figures.forEach(el=>el.style.fontSize='');
 const baseSize=Math.min(...figures.map(el=>parseFloat(getComputedStyle(el).fontSize)));
 const ratio=Math.min(1,...figures.map(el=>el.clientWidth>0?el.clientWidth/el.scrollWidth:1));
 if(ratio<1)figures.forEach(el=>el.style.fontSize=(baseSize*ratio)+'px');
}
const kpiObserver=new ResizeObserver(fitFigures);
document.querySelectorAll('.kpi').forEach(el=>kpiObserver.observe(el));
if(document.fonts)document.fonts.ready.then(fitFigures);
