const paths={panel:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M15 3v18"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',box:'<path d="m12 2 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V7m-9 5v10M7 5l10 5"/>',truck:'<path d="M3 5h11v12H3V5Zm11 5h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v3"/>',store:'<path d="m4 3-2 6a3 3 0 0 0 5 2 3 3 0 0 0 5 0 3 3 0 0 0 5 0 3 3 0 0 0 5-2l-2-6H4Zm0 10v8h16v-8M9 21v-6h6v6"/>',chart:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 16v-4m5 4V7m5 9v-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4h.01"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',lock:'<rect x="5" y="10" width="14" height="12" rx="5"/><path d="M8 10V6a4 4 0 0 1 8 0m-4 13v-3"/>',crown:'<path d="m3 6 5 5 4-8 4 8 5-5-2 15H5L3 6Zm3 11h12"/>',search:'<circle cx="10" cy="10" r="8"/><path d="m16 16 6 6"/>',sliders:'<path d="M6 2v7m0 6v7M18 2v3m0 6v11"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="8" r="3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9m-9 12h6"/>',mail:'<rect x="3" y="5" width="18" height="15" rx="4"/><path d="m4 8 8 5 8-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',cart:'<path d="M2 3h3l3 12h11l3-9H6M8 15l-1 3h12"/><circle cx="9" cy="21" r="1.5"/><circle cx="18" cy="21" r="1.5"/>',return:'<path d="M4 9V4h5M4 4l5 5m-5 3v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-5M9 14h7m-3-3 3 3-3 3"/>',network:'<circle cx="12" cy="4" r="2"/><circle cx="4" cy="19" r="3"/><circle cx="12" cy="17" r="3"/><circle cx="20" cy="19" r="3"/><path d="M12 6v8m-8 2v-5h16v5"/>',arrow:'<path d="M6 18 18 6M7 6h11v11"/>',edit:'<path d="m4 16 12-12 4 4-12 12H4v-4Zm9-9 4 4M3 22h18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15m-8 4v7m4-7v7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="3" y="12" width="5" height="9" rx="2"/><rect x="16" y="12" width="5" height="9" rx="2"/>',helmet:'<path d="M3 14a9 9 0 0 1 18 0v5H8l-5-5Zm0 0h18M8 19l2 3h8v-3M7 5l3 7"/>',shirt:'<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4a4 4 0 0 1-8 0Z"/>',glasses:'<path d="M2 9h7l2 2h2l2-2h7l-2 9h-4l-3-6h-2l-3 6H4L2 9Zm0 0 2-5m18 5-2-5"/>',bottle:'<path d="M10 2h4v5l3 4v11H7V11l3-4V2Zm-1 12h6M10 5h4"/>',bag:'<rect x="5" y="7" width="14" height="15" rx="4"/><path d="M9 7V4a3 3 0 0 1 6 0v3M8 13h8v6H8v-6M5 9l-2 9m16-9 2 9"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.box}</svg>`}
document.querySelectorAll('[data-icon]').forEach(el=>el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon)));
document.querySelectorAll('.sidebar nav a').forEach(a=>{const text=a.lastChild;a.title=text.textContent;a.setAttribute('aria-label',text.textContent);const span=document.createElement('span');span.className='nav-label';span.textContent=text.textContent;text.replaceWith(span)});
const initial=[['Headphone','SKU-300',200,150,4000,78,'headphones','#dadfe5'],['Helmate','SKU-301',500,350,7000,120,'helmet','#ddd3ce'],['T Shirts','SKU-500',2000,560,3000,35,'shirt','#e5d6d2'],['Sunglass','SKU-501',3000,1000,5000,65,'glasses','#e4e7d7'],['Water Pot','SKU-502',1000,700,3000,24,'bottle','#d7e7f0']];
let products=initial.map((p,i)=>({id:i+1,name:p[0],sku:p[1],qty:p[2],demand:p[3],stock:p[4],price:p[5],image:p[6],tint:p[7],tags:['Fast Moving',i%2?'Low Demand':'New Arrival']}));
let sales=[{id:101,name:'Backpack',qty:215,price:100,priority:'High',image:'bag',tint:'#d4d9df'},{id:102,name:'Hand bag',qty:0,price:200,priority:'Medium',image:'bag',tint:'#ffe0b4'},{id:103,name:'Headphone',qty:100,price:78,priority:'High',image:'headphones',tint:'#dce2e8'},{id:104,name:'Bottle',qty:50,price:540,priority:'Low',image:'bottle',tint:'#dfe8eb'}];
sales.push({id:105,name:'Travel Duffel',qty:80,price:145,priority:'Medium',image:'bag',tint:'#e3decf',quarterOnly:true});
let activeTag='Fast Moving',onlyLow=false,nextId=6;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+Number(n).toLocaleString('en-US');
function thumb(p){return `<span class="thumb" style="--tint:${p.tint}">${icon(p.image)}</span>`}
function actions(p,type){return `<div class="row-actions"><button data-edit="${p.id}" data-type="${type}" aria-label="Edit ${esc(p.name)}">${icon('edit')}</button><button data-delete="${p.id}" data-type="${type}" aria-label="Delete ${esc(p.name)}">${icon('trash')}</button></div>`}
function render(){const q=document.querySelector('#search').value.toLowerCase();const rows=products.filter(p=>p.tags.includes(activeTag)&&(!onlyLow||p.qty<100)&&(p.name+' '+p.sku).toLowerCase().includes(q));document.querySelector('#inventoryRows').innerHTML=rows.map(p=>`<tr><td><div class="product-cell">${thumb(p)}<div><strong>${esc(p.name)}</strong><small>${esc(p.sku)}</small></div></div></td><td>${p.qty.toLocaleString()}</td><td>${p.demand.toLocaleString()}</td><td>${money(p.stock/1000)}K</td><td>${money(p.price)}</td><td>${actions(p,'inventory')}</td></tr>`).join('');document.querySelector('#inventoryEmpty').hidden=!!rows.length;document.querySelector('#salesRows').innerHTML=sales.filter(p=>(!p.quarterOnly||document.querySelector('#salesPeriod').value==='Quarterly')&&p.name.toLowerCase().includes(q)).map(p=>`<tr><td><div class="product-cell">${thumb(p)}<div><strong>${esc(p.name)}</strong><small class="${p.qty===0?'out':p.qty<=50?'low':''}">${p.qty===0?'Out of stock':p.qty<=50?'Low stock: '+p.qty:p.qty+' in Stock'}</small></div></div></td><td>${money(p.price)}</td><td class="priority-${p.priority.toLowerCase()}">${p.priority}</td><td>${actions(p,'sales')}</td></tr>`).join('')||'<tr><td colspan="4">No sales match your search.</td></tr>'}
const delays=[['Backpack','bag','#d4d9df'],['T Shirts','shirt','#e5d6d2'],['Helmate','helmet','#ddd3ce'],['Sunglass','glasses','#e4e7d7']];document.querySelector('#delayedRows').innerHTML=delays.map(([name,image,tint])=>`<div class="delayed-row"><div class="product-cell">${thumb({image,tint})}<div><strong>${name}</strong><small>#sku-305</small></div></div><small>3 Days</small><button data-contact="${name}">Contact</button></div>`).join('');
const dialog=document.querySelector('#dialog');function show(title,body){document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogBody').innerHTML=body;dialog.showModal()}
document.querySelector('#closeDialog').addEventListener('click',()=>dialog.close());let toastTimer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function productForm(id,type='inventory'){const p=(type==='sales'?sales:products).find(p=>p.id===id);show(p?'Edit '+p.name:'Add New Product',`<form id="productForm"><label>Product name<input name="name" maxlength="60" required value="${esc(p?.name||'')}"></label><label>Price ($)<input name="price" type="number" min="0" step="0.01" max="10000000" required value="${p?.price??''}"></label><label>Quantity<input name="qty" type="number" min="0" step="1" max="1000000" required value="${p?.qty??0}"></label><button class="dark" type="submit">${p?'Save Changes':'Add Product'}</button></form>`);document.querySelector('#productForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=data.get('name').trim();if(!name)return;const values={name,price:Number(data.get('price')),qty:Number(data.get('qty'))};if(p)Object.assign(p,values);else{products.push({id:nextId,sku:'SKU-'+(600+nextId++),...values,demand:0,stock:values.price*values.qty,image:'box',tint:'#e4e9d9',tags:['New Arrival']});selectTag('New Arrival');document.querySelector('#search').value=''}render();dialog.close();toast(p?'Product updated':'Product added to New Arrival')})}
document.querySelector('#addProduct').addEventListener('click',()=>productForm());
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),contact=e.target.closest('[data-contact]');if(edit)productForm(Number(edit.dataset.edit),edit.dataset.type);if(del){const type=del.dataset.type;const p=(type==='sales'?sales:products).find(p=>p.id===Number(del.dataset.delete));show('Delete product?',`<p>Remove <strong>${esc(p.name)}</strong> from this demo list?</p><div class="dialog-actions"><button id="cancelDelete">Cancel</button><button class="dark" id="confirmDelete">Delete Product</button></div>`);document.querySelector('#cancelDelete').onclick=()=>dialog.close();document.querySelector('#confirmDelete').onclick=()=>{if(type==='sales')sales=sales.filter(x=>x.id!==p.id);else products=products.filter(x=>x.id!==p.id);render();dialog.close();toast('Product removed')}}if(contact)show('Shipment: '+contact.dataset.contact,'<p>Delayed by 3 days. Supplier: Northline Distribution.<br>Reference: SHP-305</p><p>No supplier messaging service is connected to this preview.</p>')});
function selectTag(name){activeTag=name;document.querySelectorAll('#tags button:not(#addTag)').forEach(b=>{b.classList.toggle('active',b.textContent===name);b.setAttribute('aria-pressed',String(b.textContent===name))});render()}
document.querySelector('#tags').addEventListener('click',e=>{const b=e.target.closest('button');if(b&&b.id!=='addTag')selectTag(b.textContent)});
document.querySelector('#addTag').onclick=()=>{show('Add Tag','<form id="tagForm"><label>Tag name<input name="tag" required maxlength="25"></label><button class="dark">Create Tag</button></form>');document.querySelector('#tagForm').onsubmit=e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('tag').trim();if(!name)return;if([...document.querySelectorAll('#tags button')].some(b=>b.textContent===name)){toast('That tag already exists');return}const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed','false');document.querySelector('#tags').insertBefore(b,document.querySelector('#addTag'));selectTag(name);dialog.close()}};
document.querySelector('#search').addEventListener('input',render);document.querySelector('#findSales').onclick=()=>document.querySelector('#search').focus();let ascending=true;document.querySelector('#sortSales').onclick=()=>{sales.sort((a,b)=>ascending?a.price-b.price:b.price-a.price);ascending=!ascending;render();toast(ascending?'Price: highest first':'Price: lowest first')};
document.querySelector('#filter').onclick=()=>{show('Inventory filters',`<label><input id="lowStock" type="checkbox" ${onlyLow?'checked':''}> Only products with fewer than 100 units</label><button class="dark" id="applyFilters">Apply Filters</button>`);document.querySelector('#applyFilters').onclick=()=>{onlyLow=document.querySelector('#lowStock').checked;render();dialog.close();toast(onlyLow?'Low-stock filter applied':'Showing all stock levels')}};
const stockData=[36,42,28,31,38,45],consumeData=[24,35,24,29,27,36],names=['Electronic','Drinks','Watch','Fashion','Toys','Others'];let activePoint=3;
function curve(points){return points.map((p,i)=>i===0?`M${p[0]} ${p[1]}`:`C${points[i-1][0]+42} ${points[i-1][1]},${p[0]-42} ${p[1]},${p[0]} ${p[1]}`).join(' ')}
function chart(){const mult=document.querySelector('#period').value==='Quarterly'?1.08:1;const points=stockData.map((v,i)=>[i*100,210-(v*mult-10)/40*210]);const consumed=consumeData.map((v,i)=>[i*100,210-(v*mult-10)/40*210]);document.querySelector('#stockPath').setAttribute('d',curve(points));document.querySelector('#areaPath').setAttribute('d',curve(points)+'L500 210H0Z');document.querySelector('#consumePath').setAttribute('d',curve(consumed));document.querySelector('#chartPoints').innerHTML=points.map((p,i)=>`<button style="left:${i*20}%;top:${p[1]/210*100}%" aria-label="${names[i]}: stock ${money(stockData[i]*mult*1000)}" data-point="${i}"></button>`).join('');document.querySelector('#chartCategories').innerHTML=names.map((name,i)=>`<button data-point="${i}">${name}</button>`).join('');focusPoint(activePoint)}
function focusPoint(i){activePoint=i;const mult=document.querySelector('#period').value==='Quarterly'?1.08:1;document.querySelectorAll('[data-point]').forEach(b=>b.classList.toggle('active',Number(b.dataset.point)===i));const tip=document.querySelector('#chartTooltip');tip.querySelector('strong').textContent=money(stockData[i]*mult*1000);tip.style.left=Math.max(15,Math.min(85,i*20))+'%';document.querySelector('.chart-crosshair').style.left=i*20+'%'}
for(const event of ['mouseover','focusin','click'])document.querySelector('.stock').addEventListener(event,e=>{const b=e.target.closest('[data-point]');if(b)focusPoint(Number(b.dataset.point))});document.querySelector('#period').onchange=chart;
const details={orders:['Total Orders','2,580 orders this month, up 10% from last month.'],delivered:['Already Delivered','2,380 delivered orders. 200 orders are still awaiting completion.'],returns:['Product Returns','120 returned products in the sample dataset. Return rate is down 10% compared with the previous period.']};document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const [title,text]=details[b.dataset.detail];show(title,'<p>'+text+'</p>')});
const messages={notifications:['Notifications','Four shipments are delayed by 3 days. A restock review is waiting for approval.'],inbox:['Inbox','Northline Distribution: delivery update pending. Inventory team: monthly stock review is ready.'],upgrade:['Vault Pro','This is a design preview. No subscription or payment service is connected.'],seeRestock:['Restock recommendations','120 items flagged in this illustrative forecast. Review supplier lead times and quantities before ordering.'],allShipments:['Delayed shipments','Backpack, T Shirts, Helmate, and Sunglass are each 3 days late. Contact actions show their shipment reference.']};for(const [id,[title,text]]of Object.entries(messages))document.getElementById(id).onclick=()=>show(title,'<p>'+text+'</p>');
document.querySelector('#restock').onclick=()=>{show('Restock review','<p>Prepare a draft request for 120 items flagged by the inventory forecast.</p><button class="dark" id="draftRestock">Create Draft Request</button>');document.querySelector('#draftRestock').onclick=()=>{dialog.close();toast('Draft restock request created for this session. No order sent.')}};
document.querySelector('#salesPeriod').onchange=e=>{toast(e.target.value+' sales view selected');render()};
const sidebar=document.querySelector('.sidebar'),app=document.querySelector('.app'),mobile=matchMedia('(max-width:700px)'),backdrop=document.querySelector('#backdrop');function menu(open){sidebar.classList.toggle('open',open);backdrop.hidden=!open;document.body.classList.toggle('menu-open',open);document.querySelector('main').inert=open;sidebar.inert=mobile.matches&&!open;document.querySelector('#mobileMenu').setAttribute('aria-expanded',String(open));if(open)document.querySelector('#collapse').focus()}
document.querySelector('#collapse').onclick=()=>{if(mobile.matches){menu(false);document.querySelector('#mobileMenu').focus()}else{app.classList.toggle('collapsed');const expanded=!app.classList.contains('collapsed');document.querySelector('#collapse').setAttribute('aria-expanded',String(expanded));document.querySelector('#collapse').setAttribute('aria-label',expanded?'Collapse sidebar':'Expand sidebar')}};document.querySelector('#mobileMenu').onclick=()=>menu(true);backdrop.onclick=()=>{menu(false);document.querySelector('#mobileMenu').focus()};mobile.addEventListener('change',()=>menu(false));menu(false);
sidebar.addEventListener('keydown',e=>{if(!mobile.matches||!sidebar.classList.contains('open'))return;if(e.key==='Escape'){menu(false);document.querySelector('#mobileMenu').focus()}if(e.key==='Tab'){const list=[...sidebar.querySelectorAll('a,button')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0].focus()}}});
document.querySelectorAll('.sidebar nav a').forEach(a=>a.onclick=e=>{const key=a.getAttribute('href').slice(1);if(mobile.matches)menu(false);if(key==='inventory'||key==='shipment')return;e.preventDefault();show(a.textContent,'<p>'+({dashboard:'Your inventory overview contains order totals, stock trends, and shipment exceptions.',customers:'Customer records would appear here. No customer account is connected to this demo.',store:'Main warehouse and online store are the sample inventory locations.',report:'Use the stock chart period selector and inventory tags to review this sample dataset.',help:'Search inventory, filter tags, add or edit products, and review restocking. All changes reset on reload.',settings:'Workspace: Vault. Currency: USD. This local demo does not save account settings.',privacy:'This preview stores no personal information and sends no product records to a server.'}[key]||'Inventory workspace.')+'</p>')});render();chart();
