const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',tasks:'<rect x="7" y="3" width="13" height="16" rx="3"/><path d="M7 7H5a3 3 0 0 0-3 3v9a3 3 0 0 0 3 3h9m-3-15h5m-5 4h5m-5 4h3"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-14 5h3"/>',analytics:'<rect x="3" y="12" width="4" height="8" rx="1"/><rect x="10" y="7" width="4" height="13" rx="1"/><rect x="17" y="3" width="4" height="17" rx="1"/>',team:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4"/>',settings:'<path d="m9 3 1-2h4l1 2 3 2 2 1v4l-1 2 1 2v4l-3 1-2 2h-5l-2-2-3-1v-4l1-2-1-2V6l2-1 2-2Z"/><circle cx="12" cy="12" r="3"/>',help:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m5.6 5.6 3.6 3.6m5.6 5.6 3.6 3.6m0-12.8-3.6 3.6m-5.6 5.6-3.6 3.6"/>',logout:'<path d="M9 5V3H3v18h6v-2m-1-7h13m-4-4 4 4-4 4M13 3h4v3m0 12v3h-4"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="4"/><path d="m5 8 7 5 7-5"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9m-9 12h6"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M6 18 18 6M7 6h11v11"/>',video:'<rect x="3" y="6" width="12" height="13" rx="3"/><path d="m15 10 6-3v11l-6-3"/>',pause:'<rect x="5" y="3" width="4" height="18" rx="1"/><rect x="15" y="3" width="4" height="18" rx="1"/>',stop:'<rect x="4" y="4" width="16" height="16" rx="3"/>',play:'<path d="m6 3 15 9-15 9Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
paths.garment='<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4a4 4 0 0 1-8 0Z"/>';
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`}
document.querySelectorAll('[data-icon]').forEach(el=>el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon)));
const projects=[{name:'The Linen Edit',date:'2026-09-12',color:'#b39c79',mark:'linen',status:'Completed'},{name:'Everyday Essentials',date:'2026-09-18',color:'#689785',mark:'shirt',status:'In Progress'},{name:'Autumn / Winter 26',date:'2026-09-28',color:'#365e48',mark:'coat',status:'In Progress'},{name:'Evening in Silk',date:'2026-10-05',color:'#92778b',mark:'dress',status:'Pending'},{name:'Resort Capsule',date:'2026-10-16',color:'#b9a563',mark:'dress',status:'Pending'}];
const members=[['Ada Williams','Linen set quality check','Completed','AW','#eddbcf'],['Tunde Akin','A/W tailoring & assembly','In Progress','TA','#d5e8b2'],['Zainab Bello','Silk dress sample approval','Pending','ZB','#ddd8e9'],['David Oshodi','Resort pattern grading','In Progress','DO','#f0e1b5']];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function renderProjects(){const query=document.querySelector('#search').value.toLowerCase();const visible=projects.filter(p=>p.name.toLowerCase().includes(query));document.querySelector('#projectList').innerHTML=visible.map(p=>`<button class="project-row" data-project="${projects.indexOf(p)}"><span class="project-mark" style="color:${p.color}">${icon('garment')}</span><span class="project-copy"><strong>${escapeHtml(p.name)}</strong><small>Launch: ${new Date(p.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</small></span></button>`).join('');document.querySelector('#empty').hidden=visible.length>0;document.querySelector('.sidebar nav b').textContent=projects.length}
function renderMembers(){document.querySelector('#teamList').innerHTML=members.map(([name,task,status,face,color])=>`<div class="member"><span class="avatar" style="background:${color}">${face}</span><div class="member-copy"><strong>${escapeHtml(name)}</strong><div class="member-line"><p><span>Working on </span>${escapeHtml(task)}</p><span class="tag ${status==='Pending'?'pending':status==='In Progress'?'running':''}">${status}</span></div></div></div>`).join('')}
const dialog=document.querySelector('#dialog');function show(title,body){document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogBody').innerHTML=body;dialog.showModal()}
document.querySelector('#close').addEventListener('click',()=>dialog.close());
let toastTimeout;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),3500)}
function addProject(){show('Add Collection','<form id="projectForm"><label>Collection name<input name="name" required maxlength="80" placeholder="e.g. Summer Linen Edit"></label><label>Launch date<input name="date" type="date" required></label><button class="primary">Create Collection</button></form>');document.querySelector('#projectForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=data.get('name').trim();if(!name)return;projects.push({name,date:data.get('date'),status:'Pending',color:'#257a53',mark:'◇'});document.querySelector('#search').value='';renderProjects();dialog.close();toast('Collection created')})}
document.querySelector('#addProject').addEventListener('click',addProject);document.querySelector('#newProject').addEventListener('click',addProject);document.querySelector('#search').addEventListener('input',renderProjects);
document.querySelector('#projectList').addEventListener('click',event=>{const button=event.target.closest('[data-project]');if(!button)return;const p=projects[button.dataset.project];show(p.name,`<p>Status: <strong>${p.status}</strong></p><p>Launch: ${p.date}</p>`)});
document.querySelector('#addMember').addEventListener('click',()=>{show('Add team member','<form id="memberForm"><label>Name<input name="name" required maxlength="50"></label><label>Production assignment<input name="task" required maxlength="70"></label><button class="primary">Add Member</button></form>');document.querySelector('#memberForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(!data.get('name').trim()||!data.get('task').trim())return;members.push([data.get('name').trim(),data.get('task').trim(),'In Progress',data.get('name').trim().split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase(),'#d5e8b2']);renderMembers();dialog.close();toast('Member added to this demo')})});
document.querySelector('#importData').addEventListener('click',()=>{show('Import collections','<p>Choose a JSON file containing an array of collections. Each collection needs a name and a launch date.</p><pre>[{"name":"New collection","date":"2026-09-28"}]</pre><button class="primary" id="chooseFile">Choose JSON file</button>');document.querySelector('#chooseFile').addEventListener('click',()=>document.querySelector('#fileInput').click())});
document.querySelector('#fileInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1000000)throw new Error('Choose a file smaller than 1 MB.');const data=JSON.parse(await file.text());if(!Array.isArray(data)||!data.length||data.length>100||!data.every(p=>typeof p.name==='string'&&p.name.trim()&&p.name.length<=80&&typeof p.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(p.date)&&!isNaN(Date.parse(p.date))))throw new Error('Use 1–100 collections, each with a name and valid YYYY-MM-DD date.');projects.push(...data.map(p=>({name:p.name.trim(),date:p.date,status:'Pending',color:'#257a53',mark:'◇'})));document.querySelector('#search').value='';renderProjects();dialog.close();toast(`${data.length} collections imported`)}catch(error){toast(error.message)}event.target.value=''});
let seconds=5048,running=true;const timer=document.querySelector('#time');function renderTime(){timer.textContent=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}
setInterval(()=>{if(running){seconds++;renderTime()}},1000);document.querySelector('#pause').addEventListener('click',event=>{running=!running;event.currentTarget.innerHTML=icon(running?'pause':'play');event.currentTarget.setAttribute('aria-label',running?'Pause timer':'Resume timer')});document.querySelector('#stop').addEventListener('click',()=>{running=false;toast(`Time recorded: ${timer.textContent}`);seconds=0;renderTime();document.querySelector('#pause').innerHTML=icon('play');document.querySelector('#pause').setAttribute('aria-label','Start timer')});
const launchPlan='<p><strong>Autumn / Winter 2026 ? Launch 28 September</strong></p><ul><li>328 garments passed quality check and are ready.</li><li>400 garments are in sewing and finishing.</li><li>72 garments are in cutting.</li></ul><p>800 garments planned. Next milestone: approve fit samples on 10 September.</p>';
document.querySelector('#meeting').addEventListener('click',()=>show('A/W sample review','<p>Today, 2 pm ? Design studio</p><ul><li>Check blazer shoulder fit in sizes S, M and L.</li><li>Approve trouser inseam and hem allowance.</li><li>Confirm olive and sand fabric colourways.</li></ul><p>Bring fit samples, measurement sheets, and fabric swatches.</p>'));
document.querySelector('#inbox').addEventListener('click',()=>show('Studio messages','<p><strong>Ada Williams:</strong> Linen sets passed final quality checks.</p><p><strong>Tunde Akin:</strong> A/W tailoring is in progress; fit samples are ready for review.</p>'));
document.querySelector('#notifications').addEventListener('click',()=>show('Needs attention','<p>24 paid orders await dispatch. Courier pickup: 3 pm.</p><p>12 size and colour variants have fewer than 10 available units.</p>'));
document.querySelector('#download').addEventListener('click',()=>show('Collection launch plan',launchPlan));
const metricDetails={sales:['September net sales','<p><strong>&#8358;24.8 million</strong> after discounts and returns, up 14.8% from August.</p><p>Online store: &#8358;16.2m<br>Studio: &#8358;5.4m<br>Wholesale: &#8358;3.2m</p>'],orders:['Dispatch queue','<p>24 paid orders await dispatch. Examples:</p><ul><li>AT-1048 ? Linen set ? Sand / M ? Packing</li><li>AT-1049 ? Wrap dress ? Olive / L ? Ready for courier</li><li>AT-1050 ? Tailored trousers ? Black / S ? Picking</li></ul>'],production:['Production overview',launchPlan],stock:['Low-stock variants','<p>12 variants are below the 10-unit reorder point. Examples:</p><ul><li>Linen set ? Sand / M: 4 available</li><li>Wrap dress ? Olive / L: 6 available</li><li>Tailored trousers ? Black / S: 3 available</li></ul>']};
document.querySelectorAll('[data-metric]').forEach(button=>button.addEventListener('click',()=>show(...metricDetails[button.dataset.metric])));
document.querySelectorAll('.sidebar nav a').forEach(link=>link.addEventListener('click',event=>{const key=link.getAttribute('href').slice(1);if(['dashboard','tasks','analytics','team'].includes(key))return;event.preventDefault();const views={calendar:['Launch calendar','<ul>'+projects.map(p=>`<li>${escapeHtml(p.name)} ? ${p.date}</li>`).join('')+'</ul>'],settings:['Brand workspace','<p>Atelier ? Amara Okafor</p><p>Currency: NGN ? Collection season: Autumn / Winter 2026</p><p>This design demo does not store account settings.</p>'],help:['Explore Atelier','<p>Search collections, create a collection, assign production work, import a JSON collection list, and track sample room time.</p><p>All figures are illustrative. Changes reset when you reload.</p>'],logout:['Demo account','<p>This local design concept has no signed-in account.</p>']};show(...views[key])}));
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='f'){event.preventDefault();document.querySelector('#search').focus()}});
renderProjects();renderMembers();renderTime();
