const values=[26,28,32,43,64,88,88,63,39,29,26,26,23,23,26,28,29,42,64];let scale=1;
function renderBars(){document.querySelector('#bars').innerHTML=values.map((v,i)=>`<div class="bar ${i===5||i===17?'lime':''} ${i===5?'highlight':''}" tabindex="0" role="img" aria-label="Reading ${i+1}: ${(v/24.3).toFixed(2)} percent" style="--height:${Math.min(v*scale,98)}%"><b>${(v/24.3).toFixed(2)}%</b></div>`).join('')}
document.querySelector('#miniBars').innerHTML=[40,52,62,65,62,40,40].map((v,i)=>`<span class="mini-column" style="--height:${v}%"><small>${['S','M','T','W','T','F','S'][i]}</small></span>`).join('');renderBars();
const dialog=document.querySelector('#dialog');function show(title,text){document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogText').textContent=text;dialog.showModal()}
document.querySelector('#close').addEventListener('click',()=>dialog.close());
let toastTimer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
const info={'Checkup':'Your next checkup is ready to review. This local dashboard uses illustrative health data.','Daily check-in':'Daily check-in complete. Your activity checklist is available in the Progress card.','Profile':'Celeste T. Koch · @kochceles. This is a local design demo with no connected account.','Notifications':'5 updates: workout reminder, hydration reminder, activity summary, checkup reminder, and weekly report.','Wellness news':'Explore your activity, calories, and workout overview. Values and promotional copy reproduce the supplied design reference.','Analytics':'Illustrative tracker readings for the reference dashboard. These are not connected to a medical device.','Progress':'139 running activity points. Check and uncheck the activities below to update your daily list.','Learn more':'AI-BL is presented as a visual design concept. Health claims and numbers in the reference are sample content.'};
document.querySelectorAll('[data-info]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.info,info[button.dataset.info])));
document.querySelector('#menu').addEventListener('click',()=>show('Dashboard menu','Wellness · Analytics · Progress · Workout. Use the sidebar for health sections and the date controls for the reporting view.'));
document.querySelector('#about').addEventListener('click',()=>show('AI-BL','Health Records Dashboard · Example 6. A recreation of the supplied visual reference with illustrative data.'));
document.querySelectorAll('aside nav button').forEach(button=>button.addEventListener('click',()=>show(button.title,`${button.title} records are shown as sample data in this design concept.`)));
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.app').requestFullscreen()}catch{toast('Fullscreen is unavailable in this browser.')}});
document.querySelector('#refresh').addEventListener('click',()=>{renderBars();toast('Dashboard refreshed. Demo readings are up to date.')});
document.querySelector('#period').addEventListener('change',event=>{scale=event.target.selectedIndex===0?1:.85;renderBars();document.querySelector('#calories').textContent=event.target.selectedIndex===0?'19,365.29':'18,042.56';toast('Reporting period updated')});
document.querySelector('#hours').addEventListener('change',event=>{scale=event.target.value==='12h'?.72:1;renderBars();toast(`${event.target.value} tracker view selected`)});
document.querySelector('#weekly').addEventListener('click',()=>show('Weekly summary',`Reporting period: ${document.querySelector('#period').value}. 8 workouts completed, 139 running points, and 89 bpm sample heart rate.`));
document.querySelector('#zoomIn').addEventListener('click',()=>{scale=Math.min(scale+.1,1.4);renderBars()});document.querySelector('#zoomOut').addEventListener('click',()=>{scale=Math.max(scale-.1,.4);renderBars()});
document.querySelectorAll('.tabs button').forEach((button,i)=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-selected',String(b===button))});scale=1-i*.09;renderBars();toast(`${button.textContent} demo view`)}));
let goal=265;document.querySelector('#increase').addEventListener('click',()=>{goal+=10;document.querySelector('#goal').textContent=goal});document.querySelector('#decrease').addEventListener('click',()=>{goal=Math.max(0,goal-10);document.querySelector('#goal').textContent=goal});
document.querySelector('#check').addEventListener('click',()=>document.querySelectorAll('.checklist input').forEach(input=>input.checked=true));document.querySelector('#uncheck').addEventListener('click',()=>document.querySelectorAll('.checklist input').forEach(input=>input.checked=false));
document.querySelector('#getApp').addEventListener('click',()=>show('Get AI-BL','This reference recreation has no connected mobile app download.'));
let breathing=false;document.querySelector('#breathe').addEventListener('click',()=>{if(breathing)return;breathing=true;let count=2;document.querySelector('#countdown').textContent=count;const interval=setInterval(()=>{count--;document.querySelector('#countdown').textContent=count;if(count===0){clearInterval(interval);toast('Take a slow, comfortable breath.');breathing=false;document.querySelector('#countdown').textContent='2'}},1000)});
