const paths={panel:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M15 3v18"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',box:'<path d="m12 2 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V7m-9 5v10M7 5l10 5"/>',truck:'<path d="M3 5h11v12H3V5Zm11 5h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v3"/>',store:'<path d="m4 3-2 6a3 3 0 0 0 5 2 3 3 0 0 0 5 0 3 3 0 0 0 5 0 3 3 0 0 0 5-2l-2-6H4Zm0 10v8h16v-8M9 21v-6h6v6"/>',chart:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 16v-4m5 4V7m5 9v-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4h.01"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',lock:'<rect x="5" y="10" width="14" height="12" rx="5"/><path d="M8 10V6a4 4 0 0 1 8 0m-4 13v-3"/>',crown:'<path d="m3 6 5 5 4-8 4 8 5-5-2 15H5L3 6Zm3 11h12"/>',search:'<circle cx="10" cy="10" r="8"/><path d="m16 16 6 6"/>',sliders:'<path d="M6 2v7m0 6v7M18 2v3m0 6v11"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="8" r="3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9m-9 12h6"/>',mail:'<rect x="3" y="5" width="18" height="15" rx="4"/><path d="m4 8 8 5 8-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',cart:'<path d="M2 3h3l3 12h11l3-9H6M8 15l-1 3h12"/><circle cx="9" cy="21" r="1.5"/><circle cx="18" cy="21" r="1.5"/>',return:'<path d="M4 9V4h5M4 4l5 5m-5 3v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-5M9 14h7m-3-3 3 3-3 3"/>',network:'<circle cx="12" cy="4" r="2"/><circle cx="4" cy="19" r="3"/><circle cx="12" cy="17" r="3"/><circle cx="20" cy="19" r="3"/><path d="M12 6v8m-8 2v-5h16v5"/>',arrow:'<path d="M6 18 18 6M7 6h11v11"/>',edit:'<path d="m4 16 12-12 4 4-12 12H4v-4Zm9-9 4 4M3 22h18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15m-8 4v7m4-7v7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="3" y="12" width="5" height="9" rx="2"/><rect x="16" y="12" width="5" height="9" rx="2"/>',helmet:'<path d="M3 14a9 9 0 0 1 18 0v5H8l-5-5Zm0 0h18M8 19l2 3h8v-3M7 5l3 7"/>',shirt:'<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4a4 4 0 0 1-8 0Z"/>',glasses:'<path d="M2 9h7l2 2h2l2-2h7l-2 9h-4l-3-6h-2l-3 6H4L2 9Zm0 0 2-5m18 5-2-5"/>',bottle:'<path d="M10 2h4v5l3 4v11H7V11l3-4V2Zm-1 12h6M10 5h4"/>',bag:'<rect x="5" y="7" width="14" height="15" rx="4"/><path d="M9 7V4a3 3 0 0 1 6 0v3M8 13h8v6H8v-6M5 9l-2 9m16-9 2 9"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.box}</svg>`}
paths.grid=paths.chart;
paths.receipt='<path d="M5 3h14v18l-4-2-3 2-3-2-4 2V3Zm4 5h6m-6 4h6m-6 4h3"/>';
paths.shield='<path d="m12 2 9 4v6c0 5-5 9-9 10-4-1-9-5-9-10V6l9-4Z"/><path d="m8 12 3 3 5-6"/>';
paths.chevron='<path d="m6 9 6 6 6-6"/>';
paths.share='<circle cx="12" cy="5" r="3"/><circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/><path d="m10 8-3 7m7-7 3 7"/>';
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const orders=[['shirt','Premium T-Shirt','Completed','DK-1001'],['shirt','Linen Kaftan','Pending','DK-1002'],['shirt','Classic Agbada','Pending','DK-1003'],['shirt','Tailored Suit','Completed','DK-1004'],['bag','Leather Handbag','Completed','DK-1005'],['glasses','Signature Sunglasses','Completed','DK-1006'],['shirt','Cotton Overshirt','Completed','DK-1007']];
const datasets={sep:{income:193000,returns:32000,growth:40,trend:35,returnTrend:24,counts:[233,23,482],total:565,date:'Sep 10th 2026',incomeBars:[40000,30000,36000,40000,42000,37000],expenseBars:[24000,26000,23000,19000,28000,24000]},aug:{income:164000,returns:41000,growth:22,trend:18,returnTrend:12,counts:[190,35,420],total:490,date:'Aug 10th 2026',incomeBars:[30000,32000,36000,35000,34000,38000],expenseBars:[18000,22000,20000,17000,19000,21000]}};
// Revenue equals net income plus returns; income-card net values are after returns.
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderTransactions(){const q=document.querySelector('#search').value.toLowerCase();const month=document.querySelector('#range').value==='sep'?'Sep':'Aug';document.querySelector('#transactionList').innerHTML=orders.filter(p=>p.join(' ').toLowerCase().includes(q)).map(p=>`<div class="transaction"><span class="product-icon">${icon(p[0])}</span><span class="transaction-copy"><strong>${esc(p[1])}</strong><small>${month} 12th 2026</small></span><span class="transaction-status"><strong class="${p[2]==='Pending'?'pending':''}">${p[2]}</strong><small>${p[3]}</small></span></div>`).join('')||'<p class="empty">No matching transactions. Try a product name or order reference.</p>'}
function render(){const d=datasets[document.querySelector('#range').value];document.querySelector('#incomeValue').innerHTML='<sup>$</sup>'+d.income.toLocaleString();document.querySelector('#returnValue').innerHTML='<sup>$</sup>'+d.returns.toLocaleString();document.querySelector('#revenueValue').textContent='$'+d.incomeBars.reduce((a,b)=>a+b,0).toLocaleString();document.querySelector('#growth').textContent=d.growth+'%';document.querySelector('.update-card>small').textContent=d.date;document.querySelector('.metric .up').innerHTML=`&#8599; +${d.trend}% <i>from last month</i>`;document.querySelector('.metric .down').innerHTML=`&#8600; -${d.returnTrend}% <i>from last month</i>`;document.querySelector('.revenue h3 small').innerHTML=`&#8599; +${d.trend}% <i>from last month</i>`;document.querySelector('#revenueChart').innerHTML=d.incomeBars.map((v,i)=>`<span class="bar-pair" tabindex="0" role="img" aria-label="Period ${i+1}: income $${v}, expenses $${d.expenseBars[i]}"><b>Income $${v.toLocaleString()}<br>Expenses $${d.expenseBars[i].toLocaleString()}</b><i style="height:${v/500}%"></i><i style="height:${d.expenseBars[i]/500}%"></i></span>`).join('');document.querySelectorAll('.horizontal-chart>div').forEach((el,i)=>{el.querySelector('b').textContent='('+d.counts[i]+')';el.querySelector('span').style.width=d.counts[i]/5+'%'});document.querySelector('.horizontal-chart footer').innerHTML=[0,100,200,300,400,500].map(v=>'<span>'+v+'</span>').join('');document.querySelector('.donut strong').textContent=d.total;document.querySelector('.donut').setAttribute('role','img');document.querySelector('.donut').setAttribute('aria-label',`${d.total} units sold: ready-to-wear 61%, bespoke 23%, accessories 16%`);renderTransactions()}
const dialog=document.querySelector('#dialog');function show(title,content){document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogBody').innerHTML=content;dialog.showModal()}
document.querySelector('#closeDialog').onclick=()=>dialog.close();let timer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('show'),3500)}
document.querySelector('#search').addEventListener('input',renderTransactions);document.querySelector('#range').addEventListener('change',render);
document.querySelector('.add').onclick=()=>{show('Add new product','<form id="productForm"><label>Product name<input name="name" required maxlength="60" placeholder="e.g. Linen Kaftan"></label><label>Status<select name="status"><option>Pending</option><option>Completed</option></select></label><button>Add Product</button></form>');document.querySelector('#productForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=data.get('name').trim();if(!name)return;orders.unshift(['shirt',name,data.get('status'),'DK-'+(1001+orders.length)]);document.querySelector('#search').value='';renderTransactions();dialog.close();toast('Product added to this demo session')}};
document.querySelector('.performance>button').onclick=()=>{const d=datasets[document.querySelector('#range').value];show('Sales by collection',`<p>${d.total} units sold in the selected month.</p><ul><li>Ready-to-wear: 61%</li><li>Bespoke: 23%</li><li>Accessories: 16%</li></ul><p>Illustrative collection mix.</p>`)};
document.querySelector('.upgrade button').onclick=()=>show('Siohioma+','<p>A premium workspace for collections, clients, and sales reporting. No subscription or payment service is connected to this preview.</p>');document.querySelector('.role').onclick=()=>show('Sales Admin','<p>Workspace: Siohioma Fashion House</p><p>Role: Sales Administrator</p>');document.querySelector('.user').onclick=()=>show('Fandawu Punx','<p>Sales Administrator<br>fandawu6@gmail.com</p><p>This is a local demo account.</p>');document.querySelector('[aria-label="Inbox"]').onclick=()=>show('Inbox','<p>13 sample conversations.</p><p><strong>Client fitting:</strong> The tailored suit is ready for a fitting.<br><strong>Production:</strong> Kaftan fabric has arrived.</p>');document.querySelector('[aria-label="Share"]').onclick=()=>show('Export dashboard','<p>Create a PDF of this dashboard for your team.</p><button id="printReport">Print / Save as PDF</button>');dialog.addEventListener('click',e=>{if(e.target.id==='printReport'){dialog.close();window.print()}});document.querySelector('#exportPdf').onclick=()=>window.print();
document.querySelectorAll('.metric button,.transactions .title button,.sales-report .title button').forEach((b,i)=>{const titles=['Net income','Returns','Transactions','Sales report'];b.setAttribute('aria-label',titles[i]+' details');b.onclick=()=>show(titles[i],'<p>'+['Net income is sales revenue after refunds in this illustrative dataset.','Returns show the value refunded to customers in the selected month.','Search by product name, status, or order reference. New products are added to this session.','Unit counts share a common 0–500 scale for an accurate comparison.'][i]+'</p>')});
const sidebar=document.querySelector('.sidebar'),mobile=matchMedia('(max-width:760px)'),backdrop=document.querySelector('.drawer-backdrop'),menuButton=document.querySelector('.mobile-menu');const close=document.createElement('button');close.className='sidebar-close';close.type='button';close.innerHTML='&times;';close.setAttribute('aria-label','Close navigation');sidebar.prepend(close);
function menu(open){sidebar.classList.toggle('open',open);sidebar.inert=mobile.matches&&!open;document.querySelector('.main').inert=open;backdrop.hidden=!open;document.body.classList.toggle('menu-open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-controls','sidebar');if(open){sidebar.setAttribute('role','dialog');sidebar.setAttribute('aria-modal','true');sidebar.setAttribute('aria-label','Navigation');close.focus()}else{sidebar.removeAttribute('role');sidebar.removeAttribute('aria-modal');sidebar.removeAttribute('aria-label')}}menuButton.onclick=()=>menu(true);close.onclick=backdrop.onclick=()=>{menu(false);menuButton.focus()};mobile.addEventListener('change',()=>menu(false));sidebar.addEventListener('keydown',e=>{if(!mobile.matches||!sidebar.classList.contains('open'))return;if(e.key==='Escape'){menu(false);menuButton.focus()}if(e.key==='Tab'){const f=[...sidebar.querySelectorAll('a,button')].filter(x=>x.getClientRects().length);if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});
document.querySelectorAll('.sidebar nav a').forEach(a=>{const label=a.textContent.trim();a.setAttribute('aria-label',label);a.title=label;a.onclick=e=>{const key=a.getAttribute('href').slice(1);if(mobile.matches)menu(false);if(['overview','statistics','transactions'].includes(key))return;e.preventDefault();show(label,'<p>'+({customers:'Client book: fittings, measurements, purchase history, and preferred styles.',collections:'Current collections: Ready-to-wear, Bespoke, and Accessories.',messages:'13 sample client conversations. Use the inbox to review studio updates.',settings:'Currency: USD. Reporting periods: August and September 2026. Changes reset on reload.',security:'This preview has no authentication or connected account. No customer data is transmitted.'}[key]||'Siohioma workspace.')+'</p>')}});menu(false);render();
