const paths={panel:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M15 3v18"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',box:'<path d="m12 2 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V7m-9 5v10M7 5l10 5"/>',truck:'<path d="M3 5h11v12H3V5Zm11 5h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v3"/>',store:'<path d="m4 3-2 6a3 3 0 0 0 5 2 3 3 0 0 0 5 0 3 3 0 0 0 5 0 3 3 0 0 0 5-2l-2-6H4Zm0 10v8h16v-8M9 21v-6h6v6"/>',chart:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 16v-4m5 4V7m5 9v-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4h.01"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',lock:'<rect x="5" y="10" width="14" height="12" rx="5"/><path d="M8 10V6a4 4 0 0 1 8 0m-4 13v-3"/>',crown:'<path d="m3 6 5 5 4-8 4 8 5-5-2 15H5L3 6Zm3 11h12"/>',search:'<circle cx="10" cy="10" r="8"/><path d="m16 16 6 6"/>',sliders:'<path d="M6 2v7m0 6v7M18 2v3m0 6v11"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="8" r="3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9m-9 12h6"/>',mail:'<rect x="3" y="5" width="18" height="15" rx="4"/><path d="m4 8 8 5 8-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',cart:'<path d="M2 3h3l3 12h11l3-9H6M8 15l-1 3h12"/><circle cx="9" cy="21" r="1.5"/><circle cx="18" cy="21" r="1.5"/>',return:'<path d="M4 9V4h5M4 4l5 5m-5 3v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-5M9 14h7m-3-3 3 3-3 3"/>',network:'<circle cx="12" cy="4" r="2"/><circle cx="4" cy="19" r="3"/><circle cx="12" cy="17" r="3"/><circle cx="20" cy="19" r="3"/><path d="M12 6v8m-8 2v-5h16v5"/>',arrow:'<path d="M6 18 18 6M7 6h11v11"/>',edit:'<path d="m4 16 12-12 4 4-12 12H4v-4Zm9-9 4 4M3 22h18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15m-8 4v7m4-7v7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="3" y="12" width="5" height="9" rx="2"/><rect x="16" y="12" width="5" height="9" rx="2"/>',helmet:'<path d="M3 14a9 9 0 0 1 18 0v5H8l-5-5Zm0 0h18M8 19l2 3h8v-3M7 5l3 7"/>',shirt:'<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4a4 4 0 0 1-8 0Z"/>',glasses:'<path d="M2 9h7l2 2h2l2-2h7l-2 9h-4l-3-6h-2l-3 6H4L2 9Zm0 0 2-5m18 5-2-5"/>',bottle:'<path d="M10 2h4v5l3 4v11H7V11l3-4V2Zm-1 12h6M10 5h4"/>',bag:'<rect x="5" y="7" width="14" height="15" rx="4"/><path d="M9 7V4a3 3 0 0 1 6 0v3M8 13h8v6H8v-6M5 9l-2 9m16-9 2 9"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.box}</svg>`}
paths.grid=paths.chart;
paths.layers='<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>';
paths.wallet='<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 8V5l14-3v3m4 7h-6v5h6m-3-2.5h.01"/>';
paths.chevron='<path d="m6 9 6 6 6-6"/>';
paths.calendar='<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3"/>';
paths.download='<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>';
paths.left='<path d="m15 6-6 6 6 6"/>';
paths.right='<path d="m9 6 6 6-6 6"/>';
paths.more='<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>';
paths.grid='<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>';
paths.receipt='<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 8h10m-3-3 3 3-3 3M17 16H7m3-3-3 3 3 3"/>';
paths.target='<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m12 12 9-9m-5 0h5v5"/>';
paths.coins='<circle cx="9" cy="9" r="6"/><path d="M15 8a7 7 0 1 1-7 7M9 6v6m2-5H8a1 1 0 0 0 0 2h2a1 1 0 0 1 0 2H7"/>';
paths.logout='<path d="M10 3H5v18h5m-1-9h12m-4-4 4 4-4 4"/>';
paths.sun='<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>';
paths.moon='<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>';
document.querySelectorAll('[data-icon]').forEach(el=>el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon)));

const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usd=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const figure=v=>usd(v).replace(/(\.\d{2})$/,'<span>$1</span>');
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul'];
const incomeHistory=[10000,11000,10000,14000,13000,8000,8500];
const expenseHistory=[8500,13000,9000,12500,12500,6076,6222];
const summaries={jul:{balance:15700,income:8500,expense:6222,savings:32913},jun:{balance:14005,income:8000,expense:6076,savings:29360}};
const priorJune={balance:12800,income:7600,expense:5900,savings:27000};
const budgets=[['Cafe & Restaurants',2250,'#8869fa'],['Entertainment',1500,'#c3b3fb'],['Investments',1000,'#ebe5fc'],['Food & Groceries',500,'#35333d'],['Health & Beauty',300,'#8f8c97'],['Traveling',400,'#c7c5ce']];
const goals=[{name:'MacBook Pro',target:1650,percent:25},{name:'New car',target:60000,percent:42},{name:'New house',target:150000,percent:3}];
const payments=[['25','12:30',10,'YouTube','visa','Subscription','▶','#ff0000','#fff'],['26','15:00',150,'Reserved','mastercard','Shopping','R','#fff','#111'],['27','9:00',80,'Yaposhka','mastercard','Cafe & Restaurants','Y','#fff0f7','#dc529a'],['23','10:15',12,'Spotify','visa','Entertainment','♪','#1ed760','#111'],['22','16:45',95,'Whole Foods','mastercard','Food & Groceries','W','#eaf4e8','#387445'],['21','11:20',45,'City Fitness','visa','Health & Beauty','F','#eee8fd','#8869fa']];
const widgetNames={flow:'Money flow',budget:'Budget',transactions:'Recent transactions',goals:'Saving goals',networth:'Net worth'};
const period=()=>$('#month').value;
function show(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal()}
$('#dialog').setAttribute('aria-labelledby','dialogTitle');
$('#closeDialog').onclick=()=>$('#dialog').close();
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function list(items){return '<div class="detail-list">'+items.map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join('')+'</div>'}

function renderSummary(){const data=summaries[period()],previous=period()==='jul'?summaries.jun:priorJune;Object.entries(data).forEach(([key,value])=>{const el=$('#'+key);el.innerHTML=figure(value);const delta=(value/previous[key]-1)*100,badge=el.nextElementSibling.querySelector('.trend');badge.textContent=(delta>=0?'↑ ':'↓ ')+Math.abs(delta).toFixed(1)+'%';badge.className='trend '+((key==='expense'?delta<=0:delta>=0)?'positive':'negative')});$('#networthValue').textContent=usd(data.balance+data.savings)}
function flowData(){let data=months.slice(0,period()==='jul'?7:6).map((name,i)=>({name,income:incomeHistory[i],expense:expenseHistory[i]}));if($('#year').value==='quarter')data=data.slice(-3);const fraction=$('#flowAccount').value==='all'?1:$('#flowAccount').value==='visa'?.7:.3;return data.map(d=>({...d,income:Math.round(d.income*fraction),expense:Math.round(d.expense*fraction)}))}
function hideTooltip(){$('#flowTooltip').hidden=true;$('.plot').classList.remove('focused');document.querySelectorAll('.month-bars').forEach(el=>el.classList.remove('active'))}
function renderFlow(){hideTooltip();const data=flowData(),max=15000,width=700/data.length,y=v=>125-v/max*125;$('#axis').innerHTML=[15000,10000,5000,0].map(v=>`<span style="top:${y(v)}px">${v?'$'+(v/1000).toFixed(0)+',000':'$0'}</span>`).join('');$('#flowSvg').innerHTML=[0,5000,10000,15000].map(v=>`<line class="chart-grid" x1="0" x2="700" y1="${y(v)}" y2="${y(v)}"/>`).join('')+data.map((d,i)=>{const x=i*width+width*.16,w=width*.3;return `<g class="month-bars" data-month="${i}"><rect class="income-bar" x="${x}" y="${y(d.income)}" width="${w}" height="${125-y(d.income)}" rx="9"/><rect class="expense-bar" x="${x+w+3}" y="${y(d.expense)}" width="${w}" height="${125-y(d.expense)}" rx="9"/></g>`}).join('');$('#monthLabels').innerHTML=data.map(d=>`<span>${d.name}</span>`).join('');$('#monthTargets').innerHTML=data.map((d,i)=>`<button data-month="${i}" aria-label="${d.name}: income ${usd(d.income)}, expenses ${usd(d.expense)}, net ${usd(d.income-d.expense)}"></button>`).join('');$('#monthTargets').querySelectorAll('button').forEach(button=>{function activate(){hideTooltip();const i=Number(button.dataset.month),d=data[i];$('.plot').classList.add('focused');$('#flowSvg').querySelector(`[data-month="${i}"]`).classList.add('active');const tooltip=$('#flowTooltip');tooltip.innerHTML=`<strong>${d.name} · ${$('#flowAccount').selectedOptions[0].textContent}</strong><div><span>Income</span><b>${usd(d.income)}</b></div><div><span>Expense</span><b>${usd(d.expense)}</b></div><div><span>Net flow</span><b>${usd(d.income-d.expense)}</b></div>`;tooltip.hidden=false;const bounds=$('.flow-chart').getBoundingClientRect(),r=button.getBoundingClientRect();tooltip.style.left=Math.max(0,Math.min(r.left-bounds.left,bounds.width-tooltip.offsetWidth))+'px'}button.onmouseenter=activate;button.onfocus=activate;button.onclick=activate;button.onmouseleave=hideTooltip;button.onblur=hideTooltip});}
function budgetData(){return budgets.map(([name,amount,color])=>({name,amount:period()==='jul'?amount:Math.round(amount*5600/5950),color}))}
function budgetDetails(index){const data=budgetData(),total=data.reduce((s,d)=>s+d.amount,0);show(index===undefined?'Monthly budget':data[index].name,list((index===undefined?data:[data[index]]).map(d=>[d.name,usd(d.amount)+' · '+Math.round(d.amount/total*100)+'%']))+'<p>Planned allocations for '+(period()==='jul'?'July':'June')+'. Actual expenses are shown separately in Money flow.</p>')}
function renderBudget(){const data=budgetData(),total=data.reduce((s,d)=>s+d.amount,0),circ=2*Math.PI*70;let offset=0;$('#budgetLegend').innerHTML=data.map((d,i)=>`<button class="budget-legend-row" data-budget="${i}" style="--color:${d.color}"><i></i>${d.name}</button>`).join('');$('#budgetSvg').innerHTML=data.map((d,i)=>{const len=d.amount/total*circ,svg=`<circle class="ring-segment" cx="90" cy="90" r="70" transform="rotate(-90 90 90)" style="--color:${d.color}" stroke-dasharray="${Math.max(1,len-9)} ${circ-Math.max(1,len-9)}" stroke-dashoffset="${-offset-4.5}" data-budget="${i}"><title>${d.name}: ${usd(d.amount)}</title></circle>`;offset+=len;return svg}).join('');$('.donut strong').innerHTML=figure(total);$('#budgetSvg').setAttribute('aria-label',`Monthly budget ${usd(total)}. Category details available in the legend.`)}
function filteredPayments(){const account=$('#transactionAccount').value,q=$('#transactionSearch').value.trim().toLowerCase();return payments.filter(r=>(account==='all'||r[4]===account)&&(r[3]+' '+r[5]).toLowerCase().includes(q))}
function renderTransactions(){const data=filteredPayments();$('#transactionRows').innerHTML=data.slice(0,3).map(r=>`<tr><td>${r[0]} ${period()==='jul'?'Jul':'Jun'} ${r[1]}</td><td class="amount">− ${usd(r[2]).replace('.00','')}</td><td><div class="payment-name"><span class="payment-mark" style="--brand-bg:${r[7]};--brand-color:${r[8]}">${r[6]}</span>${r[3]}</div></td><td>${r[4]==='visa'?'VISA •3254':'Mastercard •2154'}</td><td>${r[5]}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No matching transactions.</td></tr>'}
function goalDetails(index){const selected=index===undefined?goals:[goals[index]];show(index===undefined?'Saving goals':selected[0].name,selected.map(g=>`<div class="goal-detail"><h3>${g.name}</h3>${list([['Saved',usd(g.target*g.percent/100)],['Target',usd(g.target)],['Progress',g.percent+'%'],['Still to save',usd(g.target*(1-g.percent/100))]])}</div>`).join('')+'<p>Goals show your current earmarked savings, independent of the reporting month.</p>')}
function renderGoals(){$('#goalList').innerHTML=goals.map((g,i)=>`<button class="goal" data-goal="${i}" aria-label="${g.name}, ${g.percent}% of ${usd(g.target)} saved"><span class="goal-heading"><span>${g.name}</span><span>${usd(g.target).replace('.00','')}</span></span><span class="goal-track"><span style="width:${g.percent}%">${g.percent}%</span></span></button>`).join('')}
function render(){renderSummary();renderFlow();renderBudget();renderTransactions()}
$('#month').onchange=render;$('#flowAccount').onchange=renderFlow;$('#year').onchange=renderFlow;$('#transactionAccount').onchange=renderTransactions;$('#transactionSearch').oninput=renderTransactions;
$('#budgetDetails').onclick=()=>budgetDetails();$('#goalsDetails').onclick=()=>goalDetails();
$('#networthDetails').onclick=()=>show('Net worth',list([['Available balance',usd(summaries[period()].balance)],['Total savings',usd(summaries[period()].savings)],['Total assets',usd(summaries[period()].balance+summaries[period()].savings)]])+'<p>No liabilities have been entered in this preview.</p>');
document.addEventListener('click',e=>{const budget=e.target.closest('[data-budget]'),goal=e.target.closest('[data-goal]'),detail=e.target.closest('[data-detail]');if(budget)budgetDetails(Number(budget.dataset.budget));if(goal)goalDetails(Number(goal.dataset.goal));if(detail){const key=detail.dataset.detail;show(detail.getAttribute('aria-label').replace('View ','').replace(/^./,c=>c.toUpperCase()),list([['July',usd(summaries.jul[key])],['June',usd(summaries.jun[key])]])+'<p>Illustrative financial summary. Recent transactions show a sample of account activity.</p>')}});
$('#seeAll').onclick=()=>{const rows=filteredPayments();show('Transactions',rows.length?list(rows.map(r=>[r[0]+' '+(period()==='jul'?'Jul':'Jun')+' · '+r[3]+' · '+(r[4]==='visa'?'Visa':'Mastercard'),'−'+usd(r[2])])):'<p>No transactions found. Try another search or account.</p>')};
function reveal(name){const card=$(`[data-widget="${name}"]`);card.hidden=false;return card}
$('#searchButton').onclick=()=>{reveal('transactions');$('.transaction-search').hidden=false;$('#transactionSearch').focus();$('#transactions').scrollIntoView({behavior:'smooth',block:'nearest'})};

function manageWidgets(addOnly=false){const cards=[...document.querySelectorAll('[data-widget]')],hidden=cards.filter(c=>c.hidden);if(addOnly){show('Add a widget',hidden.length?'<p>Choose a widget to add to your dashboard.</p><div class="widget-options">'+hidden.map(c=>`<button class="outline" data-add="${c.dataset.widget}">${icon('plus')}${widgetNames[c.dataset.widget]}</button>`).join('')+'</div>':'<p>All available widgets are already on your dashboard. Use Manage widgets to change visibility.</p>');return}show('Manage widgets','<p>Choose what appears on your dashboard.</p><form id="widgetForm"><div class="widget-options">'+cards.map(c=>`<label><input type="checkbox" name="widget" value="${c.dataset.widget}" ${c.hidden?'':'checked'}>${widgetNames[c.dataset.widget]}</label>`).join('')+'</div><p id="widgetError" role="status"></p><button class="primary">Save layout</button></form>');$('#widgetForm').onsubmit=e=>{e.preventDefault();const selected=new FormData(e.currentTarget).getAll('widget');if(!selected.length){$('#widgetError').textContent='Keep at least one widget visible.';return}cards.forEach(c=>c.hidden=!selected.includes(c.dataset.widget));$('.dashboard-grid').classList.toggle('customized',selected.length!==4||selected.includes('networth'));$('#dialog').close();toast('Dashboard layout updated')}}
$('#manageWidgets').onclick=()=>manageWidgets();$('#addWidget').onclick=()=>manageWidgets(true);
$('#dialogBody').addEventListener('click',e=>{const button=e.target.closest('[data-add]');if(button){reveal(button.dataset.add);$('.dashboard-grid').classList.add('customized');$('#dialog').close();toast(widgetNames[button.dataset.add]+' added')}});
function theme(dark){document.body.classList.toggle('dark',dark);document.querySelectorAll('[data-theme]').forEach(button=>button.setAttribute('aria-pressed',String((button.dataset.theme==='dark')===dark)));try{localStorage.setItem('finset-theme',dark?'dark':'light')}catch{}}
try{theme(localStorage.getItem('finset-theme')==='dark')}catch{}
document.addEventListener('click',e=>{const button=e.target.closest('[data-theme]');if(button)theme(button.dataset.theme==='dark')});
const app=$('.app'),sidebar=$('#sidebar'),mobile=matchMedia('(max-width:760px)');let collapsed=false;
function menu(open){sidebar.classList.toggle('open',open);sidebar.inert=mobile.matches&&!open;$('#main').inert=open;$('#backdrop').hidden=!open;document.body.classList.toggle('menu-open',open);$('#mobileMenu').setAttribute('aria-expanded',String(open));$('#collapse').setAttribute('aria-expanded',String(mobile.matches?open:!collapsed));$('#collapse').setAttribute('aria-label',mobile.matches?'Close navigation':collapsed?'Expand sidebar':'Collapse sidebar');$('#collapse').title=$('#collapse').getAttribute('aria-label');if(open){sidebar.setAttribute('role','dialog');sidebar.setAttribute('aria-modal','true');sidebar.setAttribute('aria-label','Navigation');$('#collapse').focus()}else{sidebar.removeAttribute('role');sidebar.removeAttribute('aria-modal');sidebar.removeAttribute('aria-label')}}
$('#mobileMenu').onclick=()=>menu(true);$('#collapse').onclick=()=>{hideSectionTooltip();if(mobile.matches){menu(false);$('#mobileMenu').focus()}else{collapsed=!collapsed;app.classList.toggle('sidebar-collapsed',collapsed);menu(false)}};
$('#backdrop').onclick=()=>{menu(false);$('#mobileMenu').focus()};mobile.addEventListener('change',()=>menu(false));
sidebar.addEventListener('keydown',e=>{if(!mobile.matches||!sidebar.classList.contains('open'))return;if(e.key==='Escape'){menu(false);$('#mobileMenu').focus()}if(e.key==='Tab'){const f=[...sidebar.querySelectorAll('a,button')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});
const sectionTooltip=document.createElement('div');sectionTooltip.className='sidebar-tooltip';sectionTooltip.id='sidebar-section-tooltip';sectionTooltip.setAttribute('role','tooltip');sectionTooltip.hidden=true;document.body.append(sectionTooltip);let tooltipLink=null;
function hideSectionTooltip(){if(tooltipLink)tooltipLink.removeAttribute('aria-describedby');tooltipLink=null;sectionTooltip.classList.remove('visible');sectionTooltip.hidden=true}
function showSectionTooltip(link){if(mobile.matches||!collapsed)return;hideSectionTooltip();tooltipLink=link;sectionTooltip.textContent=link.getAttribute('aria-label');sectionTooltip.hidden=false;link.setAttribute('aria-describedby',sectionTooltip.id);const rect=link.getBoundingClientRect();sectionTooltip.style.left=Math.min(rect.right+22,innerWidth-sectionTooltip.offsetWidth-8)+'px';sectionTooltip.style.top=Math.max(8,Math.min(rect.top+(rect.height-sectionTooltip.offsetHeight)/2,innerHeight-sectionTooltip.offsetHeight-8))+'px';sectionTooltip.classList.add('visible')}
const sections={clients:['Client Book','Client profiles, measurements, style preferences, and purchase history.'],appointments:['Fittings & Styling','Fitting appointments, styling consultations, and upcoming visits.'],collections:['Collections','Seasonal collections, styles, and product availability.'],orders:['Client Orders','Bespoke and ready-to-wear orders, production status, and delivery dates.'],messages:['Conversations','Client messages, enquiries, and follow-ups.'],campaigns:['Campaigns','Collection launches, client outreach, and campaign performance.'],security:['Team & Access','Team members, workspace roles, and access permissions.']};
document.querySelectorAll('.sidebar nav a').forEach(a=>{a.removeAttribute('title');a.onmouseenter=()=>showSectionTooltip(a);a.onmouseleave=hideSectionTooltip;a.onfocus=()=>showSectionTooltip(a);a.onblur=hideSectionTooltip;a.onclick=e=>{e.preventDefault();hideSectionTooltip();if(mobile.matches){menu(false);$('#mobileMenu').focus()}const key=a.hash.slice(1);if(key==='settings'){const dark=document.body.classList.contains('dark');show('Settings','<p>Appearance</p><div class="appearance-options"><button class="outline" data-theme="light" aria-pressed="'+!dark+'">'+icon('sun')+'Light</button><button class="outline" data-theme="dark" aria-pressed="'+dark+'">'+icon('moon')+'Dark</button></div>');return}if(sections[key]){show(sections[key][0],'<p>'+sections[key][1]+'</p><p>This section is a preview; records are not connected yet.</p>');return}const target=key==='reports'?reveal('flow'):$('#dashboard');document.querySelectorAll('.sidebar nav a').forEach(link=>{link.classList.toggle('active',link===a);link.removeAttribute('aria-current')});a.setAttribute('aria-current','page');target.scrollIntoView({behavior:'smooth',block:'nearest'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}});
window.addEventListener('resize',hideSectionTooltip);window.addEventListener('scroll',hideSectionTooltip,true);document.addEventListener('keydown',e=>{if(e.key==='Escape')hideSectionTooltip()});

$('#profile').onclick=()=>show('Adaline Lively','<p>adalineel@gmail.com</p><p>Personal finance workspace · USD</p>');
$('#notifications').onclick=()=>show('Notifications',list([['Monthly review','July summary is ready'],['New car goal','42% saved'],['Budget reminder','Review your dining allocation']]));
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTooltip()});
menu(false);renderGoals();render();
